export const html = `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="企業・NPOの公開リソースと自治体資料をつなぐ、TLA共創OSの公開β版。"><title>TLA共創OS｜牧山式インテリジェンス</title><link rel="stylesheet" href="/co-creation-assets/style.css"></head>
<body><a class="skip" href="#company-name">企業検索へ</a><main class="shell">
<header><div class="brand"><span class="mark">T</span><div><strong>TLA 共創OS</strong><small>牧山式インテリジェンス × 共創リサーチ</small></div></div><span class="badge">公開β版 · v0.2</span></header>
<section class="hero"><p class="eyebrow">FROM RESOURCES TO COLLABORATION</p><h1>そのリソースから、<br>次の共創を見つける。</h1><p class="lead">企業や団体の名前を入口に、自治体の公開資料との接点を探します。<br>根拠、補完する役割、最初の対話まで、一つの画面で。</p></section>
<section class="stats" aria-label="収録状況"><div><strong id="municipality-count">—</strong><span>名称・コード台帳</span></div><div><strong>3</strong><span>詳細資料のある自治体</span></div><div><strong>9</strong><span>収録資料（終了募集を含む）</span></div><div><strong>6</strong><span>収録企業・NPO</span></div></section>
<div id="load-state" class="notice" role="status">公開データを読み込んでいます。</div>
<section class="search panel"><h2>企業・団体を調べる</h2><form id="search-form"><label for="company-name">企業・団体名</label><div class="search-row"><input id="company-name" name="company" placeholder="例：フォーバル、ベネッセ、クボタ" maxlength="120" required autocomplete="organization"><button id="search-button" type="submit" disabled>接点を解析する →</button></div><div id="examples" class="chips" aria-label="収録済み企業を選択"></div><details><summary>未収録企業の追加調査・同名法人の確認</summary><label for="official-url">公式サイトURL（同名の企業がある場合）</label><input id="official-url" type="url" placeholder="https://..." maxlength="2048"><label class="check"><input id="research-consent" type="checkbox">企業名・URLをOpenAIへ送信して調査することに同意します。非公開情報や個人の連絡先は入力しません。</label><p id="research-state" class="muted">追加調査の設定を確認中です。</p></details></form><p id="feedback" role="status" aria-live="polite"></p></section>
<section id="results" class="results" aria-live="polite" hidden></section>
<section class="panel registry"><div class="section-head"><h2>全国の名称台帳</h2><span class="muted">詳細調査済みとは限りません</span></div><label for="municipality-search">自治体名・都道府県・コードで検索</label><input id="municipality-search" placeholder="例：うるま市、神奈川県、14210"><p id="registry-count" class="muted"></p><div class="table-wrap"><table><thead><tr><th>都道府県</th><th>自治体</th><th>コード</th><th>詳細資料</th></tr></thead><tbody id="municipalities"></tbody></table></div><button id="more" type="button" class="secondary" hidden>続きを表示</button></section>
<section class="panel"><div class="section-head"><h2>このブラウザに保存した構想</h2><button id="export" class="secondary" type="button">JSONで書き出す</button></div><p class="muted">保存はボタンを押したときだけ。このブラウザ内に保存され、他の閲覧者やサーバーには共有されません。</p><div id="saved"></div><button id="clear" class="text-button" type="button">保存した構想をすべて削除</button></section>
<section class="panel notes"><h2>使う前に知っておいていただきたいこと</h2><p>照合は公開情報の13分野タグに基づく探索です。事業性の予測、自治体や政策の評価、参加・紹介の承諾ではありません。足りないタグは「未確認の役割」であり、能力不足の認定ではありません。</p><p>名称台帳は国土地理院の掲載データから取得し、政令市の行政区等の重複を除外します。元データの最終変更日として確認した日付は2024年1月9日です。最新の総務省台帳との完全な突合は未実施です。人口・予算等の数値統計は未取得です。</p><p>資料の収録日は2026年9月26日。現在も計画・事業・募集が続いているとは限りません。リンク先の原資料と当事者に確認してください。全文転載・全議事録分析ではなく、公開ページの要約です。公開プロフィールにある組織はTLAの会員や参加者と認定したものではありません。</p><details><summary>プライバシー・費用・出典</summary><p>収録済み企業の照合はブラウザ内で行います。追加AI調査は設定が有効な場合に限り、同意後に企業名・URLをOpenAIへ送信します。結果は自動公開・DB蓄積しません。アクセス時にはホスティング事業者の運用ログが残る場合があります。</p><p>追加調査は全体でUTC日付ごとに30回、送信元単位で3回を上限とする設計です。失敗時も1枠を消費します。制限用DBには日替わりのHMAC識別子と回数を保存し、7日超のデータは次回利用時に削除します。IPアドレス自体や企業名はこの制限テーブルに保存しません。</p><p><a href="https://github.com/gsi-cyberjapan/gsimaps/blob/gh-pages/js/muni.js" target="_blank" rel="noopener noreferrer">名称台帳の原データ</a> ／ <a href="https://www.gsi.go.jp/kikakuchousei/kikakuchousei40182.html" target="_blank" rel="noopener noreferrer">地理院コンテンツ利用規約</a></p><div id="source-list"></div></details></section>
<footer>TLA 共創OS · 公開情報から、対話のきっかけへ。<span>Powered by 牧山式インテリジェンス</span></footer>
</main><noscript>このページの検索にはJavaScriptが必要です。</noscript><script type="module" src="/co-creation-assets/app.mjs"></script></body></html>`;
