import test from 'node:test';
import assert from 'node:assert/strict';
import seed from '../lib/co-creation/seed.mjs';
import {normalize,safeUrl,lookup,parseGsi,match,validateInput,parseResearch} from '../lib/co-creation/core.mjs';
import {html} from '../lib/co-creation/page.mjs';
test('legal-form and full-width normalization',()=>assert.equal(normalize(' 株式会社 ＦＯＲＶＡＬ '),'forval'));
test('lookup uses exact normalized names, not substrings',()=>{assert.equal(lookup(seed,'フォーバル').length,1);assert.equal(lookup(seed,'フォー').length,0);assert.equal(lookup(seed,'').length,0);});
test('all curated resources reference existing sources',()=>{for(const c of seed.companies)for(const r of c.resources){assert.ok(seed.sources.some(s=>s.id===r.source_id));assert.ok(seed.tags[r.tag]);}});
test('all evidence references sources',()=>{for(const e of seed.evidence)assert.ok(seed.sources.some(s=>s.id===e.source_id));});
test('safe https links only',()=>{for(const u of ['javascript:alert(1)','http://example.com','https://127.0.0.1','https://[::1]','https://user:pass@example.com','https://example.local','https://host:443','https://example.com:999'])assert.equal(safeUrl(u),null);assert.equal(safeUrl('https://example.com/#x'),'https://example.com/');});
test('closed solicitations never matched',()=>{for(const c of seed.companies)assert.ok(match(seed,c,seed.fallbackMunicipalities).every(m=>m.evidence.status!=='closed'));});
test('existing activities retain status',()=>assert.ok(match(seed,lookup(seed,'フォーバル')[0],seed.fallbackMunicipalities).some(m=>m.evidence.status==='existing')));
test('nonresearch municipality gets no invented evidence',()=>assert.equal(match(seed,seed.companies[0],[{code:'01100',name:'札幌市'}]).length,0));
test('matches sorted by code, not policy score',()=>{const a=match(seed,seed.companies[0],seed.fallbackMunicipalities);assert.deepEqual(a.map(m=>m.municipality.code),a.map(m=>m.municipality.code).sort());for(const m of a)assert.equal(m.score,undefined);});
test('partners only sourced and distinct companies',()=>{for(const c of seed.companies)for(const m of match(seed,c,seed.fallbackMunicipalities))for(const p of m.partners){assert.notEqual(p.id,c.id);assert.ok(seed.companies.some(x=>x.id===p.id));assert.ok(p.source_ids.length);}});
test('input requires consent',()=>assert.throws(()=>validateInput({name:'テスト企業'})));
test('input rejects oversized or injected names',()=>{for(const name of ['x','<script>','a\nb','a'.repeat(121)])assert.throws(()=>validateInput({name,consent:true}));});
test('input validates official URL',()=>{assert.throws(()=>validateInput({name:'テスト会社',officialUrl:'http://example.com',consent:true}));assert.equal(validateInput({name:' テスト会社 ',consent:true}).name,'テスト会社');});
const result=(patch={},urls=['https://example.com/','https://example.com/business'])=>({status:'completed',output:[{type:'web_search_call',action:{sources:urls.map(url=>({url}))}},{type:'message',content:[{type:'output_text',text:JSON.stringify({name:'テスト会社',official_url:'https://example.com/',ambiguous:false,resources:[{tag:'digital',description:'テスト用の資源',source_url:'https://example.com/business'}],...patch})}]}]});
test('AI accepted only with matching source URLs',()=>assert.equal(parseResearch(result(),seed,{name:'テスト会社'}).company.resources.length,1));
test('AI unknown resource source rejected',()=>assert.throws(()=>parseResearch(result({},['https://example.com/']),seed,{name:'テスト会社'})));
test('AI ambiguous or incomplete output rejected',()=>{assert.throws(()=>parseResearch(result({ambiguous:true}),seed,{name:'テスト会社'}));assert.throws(()=>parseResearch({...result(),status:'incomplete'},seed,{name:'テスト会社'}));});
test('AI mismatched official domain rejected',()=>assert.throws(()=>parseResearch(result(),seed,{name:'テスト会社',officialUrl:'https://another.example.com/'})));
test('AI unknown tags rejected',()=>assert.throws(()=>parseResearch(result({resources:[{tag:'__proto__',description:'bad',source_url:'https://example.com/business'}]}),seed,{name:'テスト会社'})));
test('registry fails closed on incomplete remote data',()=>assert.throws(()=>parseGsi('GSI.MUNI_ARRAY["1100"] = \'1,北海道,1100,札幌市\';')));
test('public page includes scope, consent, storage disclosures',()=>{for(const text of ['詳細資料のある自治体','OpenAIへ送信','このブラウザ内','未取得','2024年1月9日','追加']){assert.ok(html.includes(text),text);}assert.ok(!html.includes('sk-'));});
