import type { CrawlFrequency, Source, SourceType } from "@/lib/types";

const now = new Date().toISOString();

type SourceSeed = [
  name: string,
  source_type: SourceType,
  url: string,
  country: string,
  region: string,
  language: string,
  category: string,
  reliability_score: number,
  crawl_frequency: CrawlFrequency
];

const politicalSources: SourceSeed[] = [
  ["White House", "Government", "https://www.whitehouse.gov/briefing-room/feed/", "US", "North America", "en", "政治・国際機関", 95, "hourly"],
  ["US State Department", "Government", "https://www.state.gov/rss-feed/", "US", "North America", "en", "政治・国際機関", 94, "every_6_hours"],
  ["Federal Register", "Government", "https://www.federalregister.gov/documents/search.rss", "US", "North America", "en", "政治・国際機関", 93, "daily"],
  ["Congress.gov", "Government", "https://www.congress.gov/", "US", "North America", "en", "政治・国際機関", 92, "daily"],
  ["Congressional Research Service", "Government", "https://crsreports.congress.gov/", "US", "North America", "en", "政治・国際機関", 91, "weekly"],
  ["European Commission", "InternationalOrganization", "https://ec.europa.eu/commission/presscorner/api/rss", "EU", "Europe", "en", "政治・国際機関", 93, "every_6_hours"],
  ["European Council", "InternationalOrganization", "https://www.consilium.europa.eu/en/press/press-releases/", "EU", "Europe", "en", "政治・国際機関", 92, "daily"],
  ["European Parliament News", "InternationalOrganization", "https://www.europarl.europa.eu/news/en/rss", "EU", "Europe", "en", "政治・国際機関", 90, "daily"],
  ["United Nations News", "InternationalOrganization", "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "Global", "Global", "en", "政治・国際機関", 94, "every_6_hours"],
  ["UN Secretary-General Statements", "InternationalOrganization", "https://www.un.org/sg/en/content/sg/statement", "Global", "Global", "en", "政治・国際機関", 91, "daily"],
  ["UNDP", "InternationalOrganization", "https://www.undp.org/news-centre", "Global", "Global", "en", "政治・国際機関", 89, "daily"],
  ["WHO News", "InternationalOrganization", "https://www.who.int/news", "Global", "Global", "en", "政治・国際機関", 91, "daily"],
  ["WTO News", "InternationalOrganization", "https://www.wto.org/english/news_e/news_e.htm", "Global", "Global", "en", "政治・国際機関", 90, "daily"],
  ["OECD News", "InternationalOrganization", "https://www.oecd.org/newsroom/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "政治・国際機関", 92, "daily"],
  ["World Economic Forum Agenda", "ThinkTank", "https://www.weforum.org/agenda/feed/", "Global", "Global", "en", "政治・国際機関", 86, "daily"],
  ["NATO News", "InternationalOrganization", "https://www.nato.int/cps/en/natohq/news.xml", "Global", "Europe", "en", "政治・国際機関", 91, "daily"],
  ["G7 Hiroshima Process / Cabinet Secretariat", "Government", "https://www.cas.go.jp/", "JP", "Asia", "ja", "政治・国際機関", 89, "weekly"],
  ["日本国外務省", "Government", "https://www.mofa.go.jp/mofaj/rss/index.xml", "JP", "Asia", "ja", "政治・国際機関", 94, "daily"],
  ["内閣府", "Government", "https://www.cao.go.jp/rss/news.xml", "JP", "Asia", "ja", "政治・国際機関", 92, "daily"],
  ["首相官邸", "Government", "https://www.kantei.go.jp/", "JP", "Asia", "ja", "政治・国際機関", 92, "daily"],
  ["総務省", "Government", "https://www.soumu.go.jp/menu_news/index.html", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["デジタル庁", "Government", "https://www.digital.go.jp/news", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["防衛省", "Government", "https://www.mod.go.jp/j/press/news/", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["CSIS", "ThinkTank", "https://www.csis.org/rss.xml", "US", "Global", "en", "政治・国際機関", 88, "daily"],
  ["RAND Corporation", "ThinkTank", "https://www.rand.org/pubs.xml", "US", "Global", "en", "政治・国際機関", 88, "weekly"],
  ["Chatham House", "ThinkTank", "https://www.chathamhouse.org/rss.xml", "UK", "Global", "en", "政治・国際機関", 88, "daily"],
  ["Council on Foreign Relations", "ThinkTank", "https://www.cfr.org/rss.xml", "US", "Global", "en", "政治・国際機関", 88, "daily"],
  ["IISS", "ThinkTank", "https://www.iiss.org/rss", "UK", "Global", "en", "政治・国際機関", 86, "weekly"],
  ["Brookings Foreign Policy", "ThinkTank", "https://www.brookings.edu/feed/", "US", "Global", "en", "政治・国際機関", 87, "daily"],
  ["Carnegie Endowment", "ThinkTank", "https://carnegieendowment.org/rss/solr/?fa=feeds", "US", "Global", "en", "政治・国際機関", 87, "daily"]
];

const economicSources: SourceSeed[] = [
  ["IMF", "InternationalOrganization", "https://www.imf.org/en/News/RSS", "Global", "Global", "en", "経済・金融", 95, "daily"],
  ["World Bank", "InternationalOrganization", "https://www.worldbank.org/en/news/all/rss", "Global", "Global", "en", "経済・金融", 94, "daily"],
  ["BIS", "InternationalOrganization", "https://www.bis.org/list/press_releases/index.rss", "Global", "Global", "en", "経済・金融", 94, "daily"],
  ["Federal Reserve", "Government", "https://www.federalreserve.gov/feeds/press_all.xml", "US", "North America", "en", "経済・金融", 95, "daily"],
  ["European Central Bank", "Government", "https://www.ecb.europa.eu/rss/press.html", "EU", "Europe", "en", "経済・金融", 94, "daily"],
  ["Bank of Japan", "Government", "https://www.boj.or.jp/rss/whatsnew.xml", "JP", "Asia", "ja", "経済・金融", 95, "daily"],
  ["US Treasury", "Government", "https://home.treasury.gov/news/press-releases", "US", "North America", "en", "経済・金融", 93, "daily"],
  ["US Bureau of Economic Analysis", "Government", "https://www.bea.gov/news", "US", "North America", "en", "経済・金融", 92, "daily"],
  ["US Bureau of Labor Statistics", "Government", "https://www.bls.gov/bls/news-release/home.htm", "US", "North America", "en", "経済・金融", 92, "daily"],
  ["FRED Blog", "Government", "https://fredblog.stlouisfed.org/feed/", "US", "North America", "en", "経済・金融", 89, "weekly"],
  ["OECD Economy", "InternationalOrganization", "https://www.oecd.org/economy/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "経済・金融", 91, "weekly"],
  ["OECD Tax", "InternationalOrganization", "https://www.oecd.org/tax/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "経済・金融", 89, "weekly"],
  ["World Trade Organization", "InternationalOrganization", "https://www.wto.org/english/news_e/news_e.htm", "Global", "Global", "en", "経済・金融", 90, "daily"],
  ["International Energy Agency", "InternationalOrganization", "https://www.iea.org/news", "Global", "Global", "en", "経済・金融", 89, "daily"],
  ["UNCTAD", "InternationalOrganization", "https://unctad.org/news", "Global", "Global", "en", "経済・金融", 88, "daily"],
  ["Asian Development Bank", "InternationalOrganization", "https://www.adb.org/news", "Asia", "Asia", "en", "経済・金融", 89, "daily"],
  ["財務省", "Government", "https://www.mof.go.jp/rss/index.xml", "JP", "Asia", "ja", "経済・金融", 93, "daily"],
  ["経済産業省", "Government", "https://www.meti.go.jp/rss/main.xml", "JP", "Asia", "ja", "経済・金融", 92, "daily"],
  ["金融庁", "Government", "https://www.fsa.go.jp/news/", "JP", "Asia", "ja", "経済・金融", 92, "daily"],
  ["日本取引所グループ", "NewsMedia", "https://www.jpx.co.jp/news/", "JP", "Asia", "ja", "経済・金融", 86, "daily"],
  ["Nikkei Asia", "NewsMedia", "https://asia.nikkei.com/rss/feed/nar", "JP", "Asia", "en", "経済・金融", 83, "hourly"],
  ["Financial Times World Economy", "NewsMedia", "https://www.ft.com/world-economy", "Global", "Global", "en", "経済・金融", 82, "daily"],
  ["The Economist", "NewsMedia", "https://www.economist.com/", "Global", "Global", "en", "経済・金融", 82, "daily"],
  ["McKinsey Insights", "ThinkTank", "https://www.mckinsey.com/featured-insights", "Global", "Global", "en", "経済・金融", 84, "weekly"],
  ["BCG Insights", "ThinkTank", "https://www.bcg.com/publications", "Global", "Global", "en", "経済・金融", 83, "weekly"],
  ["Deloitte Insights", "ThinkTank", "https://www2.deloitte.com/us/en/insights.html", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["Goldman Sachs Insights", "ThinkTank", "https://www.goldmansachs.com/insights/", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["BlackRock Insights", "ThinkTank", "https://www.blackrock.com/corporate/insights", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["Peterson Institute", "ThinkTank", "https://www.piie.com/rss.xml", "US", "Global", "en", "経済・金融", 87, "daily"],
  ["Bruegel", "ThinkTank", "https://www.bruegel.org/rss.xml", "EU", "Europe", "en", "経済・金融", 86, "daily"]
];

const thoughtSources: SourceSeed[] = [
  ["Pew Research Center", "ThinkTank", "https://www.pewresearch.org/feed/", "US", "Global", "en", "思想・社会", 89, "daily"],
  ["World Values Survey", "Academic", "https://www.worldvaluessurvey.org/rss/rss.xml", "Global", "Global", "en", "思想・社会", 86, "weekly"],
  ["Our World in Data", "Academic", "https://ourworldindata.org/atom.xml", "Global", "Global", "en", "思想・社会", 89, "daily"],
  ["UNESCO", "InternationalOrganization", "https://www.unesco.org/en/rss.xml", "Global", "Global", "en", "思想・社会", 91, "daily"],
  ["UNESCO Social and Human Sciences", "InternationalOrganization", "https://www.unesco.org/en/social-human-sciences", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["OECD Society", "InternationalOrganization", "https://www.oecd.org/social/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["OECD Education", "InternationalOrganization", "https://www.oecd.org/education/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["World Bank Education", "InternationalOrganization", "https://www.worldbank.org/en/topic/education/rss", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["UNICEF Research", "InternationalOrganization", "https://www.unicef-irc.org/", "Global", "Global", "en", "思想・社会", 88, "weekly"],
  ["ILO News", "InternationalOrganization", "https://www.ilo.org/global/about-the-ilo/newsroom/news/lang--en/index.htm", "Global", "Global", "en", "思想・社会", 88, "daily"],
  ["Migration Policy Institute", "ThinkTank", "https://www.migrationpolicy.org/rss.xml", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["Gallup News", "ThinkTank", "https://news.gallup.com/rss.aspx", "US", "Global", "en", "思想・社会", 84, "daily"],
  ["Edelman Trust Barometer", "ThinkTank", "https://www.edelman.com/trust", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["Ipsos Global Advisor", "ThinkTank", "https://www.ipsos.com/en/global-advisor", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["DataReportal", "ThinkTank", "https://datareportal.com/reports", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["Berkman Klein Center", "Academic", "https://cyber.harvard.edu/news", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["Stanford Center on Philanthropy and Civil Society", "Academic", "https://pacscenter.stanford.edu/research/", "US", "Global", "en", "思想・社会", 84, "weekly"],
  ["Harvard Kennedy School News", "Academic", "https://www.hks.harvard.edu/faculty-research/policy-topics", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["LSE Blogs", "Academic", "https://blogs.lse.ac.uk/", "UK", "Global", "en", "思想・社会", 84, "daily"],
  ["Brookings Social Policy", "ThinkTank", "https://www.brookings.edu/feed/", "US", "Global", "en", "思想・社会", 86, "daily"],
  ["Urban Institute", "ThinkTank", "https://www.urban.org/rss.xml", "US", "North America", "en", "思想・社会", 85, "weekly"],
  ["日本総研", "ThinkTank", "https://www.jri.co.jp/page.jsp?id=147", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["NIRA総合研究開発機構", "ThinkTank", "https://www.nira.or.jp/", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["リクルートワークス研究所", "ThinkTank", "https://www.works-i.com/", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["文部科学省", "Government", "https://www.mext.go.jp/rss/news.xml", "JP", "Asia", "ja", "思想・社会", 93, "daily"],
  ["厚生労働省", "Government", "https://www.mhlw.go.jp/stf/news.rdf", "JP", "Asia", "ja", "思想・社会", 92, "daily"],
  ["こども家庭庁", "Government", "https://www.cfa.go.jp/news", "JP", "Asia", "ja", "思想・社会", 90, "daily"],
  ["文化庁", "Government", "https://www.bunka.go.jp/koho_hodo_oshirase/hodohappyo/", "JP", "Asia", "ja", "思想・社会", 89, "weekly"],
  ["内閣府 男女共同参画局", "Government", "https://www.gender.go.jp/public/index.html", "JP", "Asia", "ja", "思想・社会", 89, "weekly"],
  ["United Nations Population Fund", "InternationalOrganization", "https://www.unfpa.org/news", "Global", "Global", "en", "思想・社会", 88, "daily"]
];

const technologySources: SourceSeed[] = [
  ["OpenAI Blog", "Website", "https://openai.com/news/rss.xml", "US", "Global", "en", "テクノロジー", 90, "daily"],
  ["Google DeepMind Blog", "Website", "https://deepmind.google/discover/blog/rss.xml", "UK", "Global", "en", "テクノロジー", 90, "daily"],
  ["Google AI Blog", "Website", "https://blog.google/technology/ai/rss/", "US", "Global", "en", "テクノロジー", 88, "daily"],
  ["Microsoft AI Blog", "Website", "https://blogs.microsoft.com/ai/feed/", "US", "Global", "en", "テクノロジー", 88, "daily"],
  ["Meta AI Blog", "Website", "https://ai.meta.com/blog/", "US", "Global", "en", "テクノロジー", 87, "daily"],
  ["Anthropic News", "Website", "https://www.anthropic.com/news", "US", "Global", "en", "テクノロジー", 87, "daily"],
  ["NVIDIA Blog", "Website", "https://blogs.nvidia.com/feed/", "US", "Global", "en", "テクノロジー", 86, "daily"],
  ["Intel Newsroom", "Website", "https://www.intel.com/content/www/us/en/newsroom/home.html", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["AMD Newsroom", "Website", "https://www.amd.com/en/newsroom.html", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["TSMC News", "Website", "https://pr.tsmc.com/english/news", "TW", "Asia", "en", "テクノロジー", 85, "daily"],
  ["ASML News", "Website", "https://www.asml.com/en/news", "NL", "Europe", "en", "テクノロジー", 85, "daily"],
  ["MIT Technology Review", "NewsMedia", "https://www.technologyreview.com/feed/", "US", "Global", "en", "テクノロジー", 85, "daily"],
  ["IEEE Spectrum", "NewsMedia", "https://spectrum.ieee.org/feeds/feed.rss", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["Nature Machine Intelligence", "Academic", "https://www.nature.com/natmachintell/", "Global", "Global", "en", "テクノロジー", 88, "weekly"],
  ["Science Robotics", "Academic", "https://www.science.org/journal/scirobotics", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["arXiv AI papers", "Academic", "http://export.arxiv.org/rss/cs.AI", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Machine Learning", "Academic", "http://export.arxiv.org/rss/cs.LG", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Computation and Language", "Academic", "http://export.arxiv.org/rss/cs.CL", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Computer Vision", "Academic", "http://export.arxiv.org/rss/cs.CV", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["Stanford HAI", "Academic", "https://hai.stanford.edu/news/rss.xml", "US", "Global", "en", "テクノロジー", 89, "weekly"],
  ["MIT CSAIL News", "Academic", "https://www.csail.mit.edu/news", "US", "Global", "en", "テクノロジー", 88, "weekly"],
  ["Berkeley AI Research", "Academic", "https://bair.berkeley.edu/blog/", "US", "Global", "en", "テクノロジー", 87, "weekly"],
  ["Allen Institute for AI", "Academic", "https://allenai.org/blog", "US", "Global", "en", "テクノロジー", 87, "weekly"],
  ["OECD AI Policy Observatory", "InternationalOrganization", "https://oecd.ai/en/wonk", "Global", "Global", "en", "テクノロジー", 89, "weekly"],
  ["NIST AI", "Government", "https://www.nist.gov/artificial-intelligence", "US", "North America", "en", "テクノロジー", 90, "weekly"],
  ["DARPA News", "Government", "https://www.darpa.mil/news", "US", "North America", "en", "テクノロジー", 88, "weekly"],
  ["National Science Foundation News", "Government", "https://new.nsf.gov/news", "US", "North America", "en", "テクノロジー", 88, "weekly"],
  ["EU AI Office", "Government", "https://digital-strategy.ec.europa.eu/en/policies/ai-office", "EU", "Europe", "en", "テクノロジー", 89, "weekly"],
  ["デジタル庁 AI", "Government", "https://www.digital.go.jp/policies/ai", "JP", "Asia", "ja", "テクノロジー", 90, "weekly"],
  ["IPA 情報処理推進機構", "Government", "https://www.ipa.go.jp/news/", "JP", "Asia", "ja", "テクノロジー", 88, "daily"],
  ["NICT News", "Government", "https://www.nict.go.jp/press/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["産総研", "Government", "https://www.aist.go.jp/aist_j/news/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["理化学研究所", "Academic", "https://www.riken.jp/press/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["JST News", "Government", "https://www.jst.go.jp/pr/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["MIT Sloan Management Review AI", "NewsMedia", "https://sloanreview.mit.edu/tag/artificial-intelligence/", "US", "Global", "en", "テクノロジー", 84, "weekly"]
];

const countryLayerSources: SourceSeed[] = [
  ["China State Council", "Government", "https://english.www.gov.cn/news/", "CN", "Asia", "en", "政治・国際機関", 89, "daily"],
  ["China Ministry of Foreign Affairs", "Government", "https://www.mfa.gov.cn/eng/wjdt_665385/", "CN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["National Bureau of Statistics of China", "Government", "https://www.stats.gov.cn/english/PressRelease/", "CN", "Asia", "en", "経済・金融", 89, "daily"],
  ["People's Bank of China", "Government", "https://www.pbc.gov.cn/en/3688110/3688172/index.html", "CN", "Asia", "en", "経済・金融", 89, "daily"],
  ["China Academy of Information and Communications Technology", "ThinkTank", "http://www.caict.ac.cn/english/research/", "CN", "Asia", "en", "テクノロジー", 84, "weekly"],
  ["Tsinghua University News", "Academic", "https://www.tsinghua.edu.cn/en/info/1245/1237.htm", "CN", "Asia", "en", "思想・社会", 82, "weekly"],
  ["India Prime Minister's Office", "Government", "https://www.pmindia.gov.in/en/news_updates/", "IN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["India Ministry of External Affairs", "Government", "https://www.mea.gov.in/press-releases.htm", "IN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Reserve Bank of India", "Government", "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx", "IN", "Asia", "en", "経済・金融", 90, "daily"],
  ["NITI Aayog", "Government", "https://www.niti.gov.in/press-releases", "IN", "Asia", "en", "経済・金融", 87, "weekly"],
  ["India Ministry of Electronics and IT", "Government", "https://www.meity.gov.in/news", "IN", "Asia", "en", "テクノロジー", 87, "weekly"],
  ["Observer Research Foundation", "ThinkTank", "https://www.orfonline.org/feed", "IN", "Asia", "en", "思想・社会", 85, "daily"],
  ["UK Government News", "Government", "https://www.gov.uk/search/news-and-communications", "UK", "Europe", "en", "政治・国際機関", 90, "daily"],
  ["Bank of England", "Government", "https://www.bankofengland.co.uk/news", "UK", "Europe", "en", "経済・金融", 91, "daily"],
  ["Office for National Statistics", "Government", "https://www.ons.gov.uk/news", "UK", "Europe", "en", "経済・金融", 90, "daily"],
  ["UK AI Safety Institute", "Government", "https://www.aisi.gov.uk/news", "UK", "Europe", "en", "テクノロジー", 89, "weekly"],
  ["The Alan Turing Institute", "Academic", "https://www.turing.ac.uk/news", "UK", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["King's College London Policy Institute", "Academic", "https://www.kcl.ac.uk/policy-institute", "UK", "Europe", "en", "思想・社会", 84, "weekly"],
  ["Germany Federal Government", "Government", "https://www.bundesregierung.de/breg-en/news", "DE", "Europe", "en", "政治・国際機関", 89, "daily"],
  ["Deutsche Bundesbank", "Government", "https://www.bundesbank.de/en/press", "DE", "Europe", "en", "経済・金融", 91, "daily"],
  ["Destatis Germany", "Government", "https://www.destatis.de/EN/Press/Press.html", "DE", "Europe", "en", "経済・金融", 90, "daily"],
  ["Germany Federal Ministry of Education and Research", "Government", "https://www.bmbf.de/bmbf/en/home/home_node.html", "DE", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["Fraunhofer News", "Academic", "https://www.fraunhofer.de/en/press.html", "DE", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["Bertelsmann Stiftung", "ThinkTank", "https://www.bertelsmann-stiftung.de/en/our-projects", "DE", "Europe", "en", "思想・社会", 84, "weekly"],
  ["France Government News", "Government", "https://www.gouvernement.fr/en/news", "FR", "Europe", "en", "政治・国際機関", 88, "daily"],
  ["Banque de France", "Government", "https://www.banque-france.fr/en/press-release", "FR", "Europe", "en", "経済・金融", 90, "daily"],
  ["INSEE France", "Government", "https://www.insee.fr/en/statistiques?debut=0", "FR", "Europe", "en", "経済・金融", 89, "daily"],
  ["Inria News", "Academic", "https://www.inria.fr/en/news", "FR", "Europe", "en", "テクノロジー", 86, "weekly"],
  ["Sciences Po Research", "Academic", "https://www.sciencespo.fr/en/research/", "FR", "Europe", "en", "思想・社会", 84, "weekly"],
  ["Korea Government", "Government", "https://www.korea.net/Government/Briefing-Room/Press-Releases", "KR", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Bank of Korea", "Government", "https://www.bok.or.kr/eng/bbs/E0000634/list.do", "KR", "Asia", "en", "経済・金融", 90, "daily"],
  ["Korea Statistics", "Government", "https://kostat.go.kr/anse/", "KR", "Asia", "en", "経済・金融", 88, "weekly"],
  ["Korea Ministry of Science and ICT", "Government", "https://www.msit.go.kr/eng/bbs/list.do?sCode=eng&mId=4&mPid=2", "KR", "Asia", "en", "テクノロジー", 88, "weekly"],
  ["Korea Development Institute", "ThinkTank", "https://www.kdi.re.kr/kdi_eng/main/main.jsp", "KR", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Taiwan Executive Yuan", "Government", "https://english.ey.gov.tw/News3", "TW", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Taiwan Central Bank", "Government", "https://www.cbc.gov.tw/en/mp-2.html", "TW", "Asia", "en", "経済・金融", 88, "weekly"],
  ["Taiwan National Development Council", "Government", "https://www.ndc.gov.tw/en/News.aspx", "TW", "Asia", "en", "経済・金融", 87, "weekly"],
  ["Taiwan Ministry of Digital Affairs", "Government", "https://moda.gov.tw/en/press/press-releases/607", "TW", "Asia", "en", "テクノロジー", 88, "weekly"],
  ["Academia Sinica", "Academic", "https://www.sinica.edu.tw/en/news", "TW", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Singapore Government News", "Government", "https://www.gov.sg/news", "SG", "Asia", "en", "政治・国際機関", 89, "daily"],
  ["Monetary Authority of Singapore", "Government", "https://www.mas.gov.sg/news", "SG", "Asia", "en", "経済・金融", 91, "daily"],
  ["Singapore Department of Statistics", "Government", "https://www.singstat.gov.sg/whats-new/latest-news", "SG", "Asia", "en", "経済・金融", 88, "weekly"],
  ["AI Singapore", "Academic", "https://aisingapore.org/news/", "SG", "Asia", "en", "テクノロジー", 87, "weekly"],
  ["Institute of Policy Studies Singapore", "ThinkTank", "https://lkyspp.nus.edu.sg/ips", "SG", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Brazil Government News", "Government", "https://www.gov.br/planalto/en/latest-news", "BR", "South America", "en", "政治・国際機関", 86, "daily"],
  ["Central Bank of Brazil", "Government", "https://www.bcb.gov.br/en/press", "BR", "South America", "en", "経済・金融", 89, "daily"],
  ["IBGE News Agency", "Government", "https://agenciadenoticias.ibge.gov.br/en/agencia-news", "BR", "South America", "en", "経済・金融", 87, "weekly"],
  ["Brazil Ministry of Science Technology and Innovation", "Government", "https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/noticias", "BR", "South America", "pt", "テクノロジー", 85, "weekly"],
  ["Ipea Brazil", "ThinkTank", "https://www.ipea.gov.br/portal/", "BR", "South America", "pt", "思想・社会", 84, "weekly"]
];

const emergingRegionSources: SourceSeed[] = [
  ["Indonesia Cabinet Secretariat", "Government", "https://setkab.go.id/en/category/news/", "ID", "Southeast Asia", "en", "政治・国際機関", 86, "daily"],
  ["Bank Indonesia", "Government", "https://www.bi.go.id/en/publikasi/ruang-media/news-release/Default.aspx", "ID", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Statistics Indonesia", "Government", "https://www.bps.go.id/en/pressrelease", "ID", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["Indonesia Ministry of Communication and Digital Affairs", "Government", "https://www.komdigi.go.id/", "ID", "Southeast Asia", "id", "テクノロジー", 84, "weekly"],
  ["CSIS Indonesia", "ThinkTank", "https://www.csis.or.id/", "ID", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Vietnam Government News", "Government", "https://en.baochinhphu.vn/", "VN", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["State Bank of Vietnam", "Government", "https://www.sbv.gov.vn/webcenter/portal/en/home/sbv/news", "VN", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["General Statistics Office Vietnam", "Government", "https://www.gso.gov.vn/en/data-and-statistics/", "VN", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["Vietnam Ministry of Science and Technology", "Government", "https://www.most.gov.vn/en/Pages/home.aspx", "VN", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Vietnam Academy of Social Sciences", "Academic", "https://en.vass.gov.vn/", "VN", "Southeast Asia", "en", "思想・社会", 82, "weekly"],
  ["Thailand Government Public Relations", "Government", "https://thailand.prd.go.th/en", "TH", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bank of Thailand", "Government", "https://www.bot.or.th/en/news-and-media/news.html", "TH", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["National Statistical Office Thailand", "Government", "https://www.nso.go.th/nsoweb/index?set_lang=en", "TH", "Southeast Asia", "en", "経済・金融", 84, "weekly"],
  ["Thailand Digital Economy Promotion Agency", "Government", "https://www.depa.or.th/en/news", "TH", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Thailand Development Research Institute", "ThinkTank", "https://tdri.or.th/en/", "TH", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Malaysia Prime Minister Office", "Government", "https://www.pmo.gov.my/news/", "MY", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bank Negara Malaysia", "Government", "https://www.bnm.gov.my/press-releases", "MY", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Department of Statistics Malaysia", "Government", "https://www.dosm.gov.my/portal-main/release-content", "MY", "Southeast Asia", "en", "経済・金融", 85, "weekly"],
  ["Malaysia Digital Economy Corporation", "Government", "https://mdec.my/news", "MY", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Khazanah Research Institute", "ThinkTank", "https://www.krinstitute.org/", "MY", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Philippines Official Gazette", "Government", "https://www.officialgazette.gov.ph/", "PH", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bangko Sentral ng Pilipinas", "Government", "https://www.bsp.gov.ph/SitePages/MediaAndResearch/MediaList.aspx", "PH", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Philippine Statistics Authority", "Government", "https://psa.gov.ph/statistics/press-releases", "PH", "Southeast Asia", "en", "経済・金融", 85, "weekly"],
  ["Philippines DICT", "Government", "https://dict.gov.ph/news/", "PH", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Philippine Institute for Development Studies", "ThinkTank", "https://www.pids.gov.ph/", "PH", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Nigeria State House", "Government", "https://statehouse.gov.ng/news/", "NG", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Nigeria", "Government", "https://www.cbn.gov.ng/Out/News.asp", "NG", "Africa", "en", "経済・金融", 86, "daily"],
  ["National Bureau of Statistics Nigeria", "Government", "https://www.nigerianstat.gov.ng/news", "NG", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Nigeria National Information Technology Development Agency", "Government", "https://nitda.gov.ng/news/", "NG", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["Centre for Democracy and Development West Africa", "ThinkTank", "https://cddwestafrica.org/", "NG", "Africa", "en", "思想・社会", 83, "weekly"],
  ["South Africa Presidency", "Government", "https://www.thepresidency.gov.za/press-statements", "ZA", "Africa", "en", "政治・国際機関", 85, "daily"],
  ["South African Reserve Bank", "Government", "https://www.resbank.co.za/en/home/publications/publication-detail-pages/media-releases", "ZA", "Africa", "en", "経済・金融", 88, "daily"],
  ["Statistics South Africa", "Government", "https://www.statssa.gov.za/?page_id=1854", "ZA", "Africa", "en", "経済・金融", 85, "weekly"],
  ["South Africa Department of Communications and Digital Technologies", "Government", "https://www.dcdt.gov.za/media-room/media-statements.html", "ZA", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["Institute for Security Studies Africa", "ThinkTank", "https://issafrica.org/iss-today", "ZA", "Africa", "en", "思想・社会", 85, "weekly"],
  ["Kenya State House", "Government", "https://www.president.go.ke/news/", "KE", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Kenya", "Government", "https://www.centralbank.go.ke/media-center/", "KE", "Africa", "en", "経済・金融", 86, "daily"],
  ["Kenya National Bureau of Statistics", "Government", "https://www.knbs.or.ke/news/", "KE", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Kenya ICT Authority", "Government", "https://icta.go.ke/media-center/news/", "KE", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["African Population and Health Research Center", "ThinkTank", "https://aphrc.org/news/", "KE", "Africa", "en", "思想・社会", 84, "weekly"],
  ["Egypt State Information Service", "Government", "https://www.sis.gov.eg/section/0/501?lang=en-us", "EG", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Egypt", "Government", "https://www.cbe.org.eg/en/news-publications/news", "EG", "Africa", "en", "経済・金融", 86, "daily"],
  ["CAPMAS Egypt", "Government", "https://www.capmas.gov.eg/HomePage.aspx?lang=2", "EG", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Egypt Information Technology Industry Development Agency", "Government", "https://www.itida.gov.eg/English/MediaCenter/News/Pages/default.aspx", "EG", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["AUC Alternative Policy Solutions", "Academic", "https://aps.aucegypt.edu/en", "EG", "Africa", "en", "思想・社会", 83, "weekly"],
  ["Mexico Presidency", "Government", "https://www.gob.mx/presidencia/prensa", "MX", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Bank of Mexico", "Government", "https://www.banxico.org.mx/publications-and-press/press-releases/%7B0%7D", "MX", "Latin America", "en", "経済・金融", 88, "daily"],
  ["INEGI Mexico", "Government", "https://www.inegi.org.mx/app/saladeprensa/", "MX", "Latin America", "es", "経済・金融", 85, "weekly"],
  ["Mexico Digital Agency", "Government", "https://www.gob.mx/innovaciondigital", "MX", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["CIDE Mexico", "Academic", "https://www.cide.edu/", "MX", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Argentina Government", "Government", "https://www.argentina.gob.ar/noticias", "AR", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Central Bank of Argentina", "Government", "https://www.bcra.gob.ar/Noticias/", "AR", "Latin America", "es", "経済・金融", 86, "daily"],
  ["INDEC Argentina", "Government", "https://www.indec.gob.ar/indec/web/Institucional-Indec-Noticias", "AR", "Latin America", "es", "経済・金融", 85, "weekly"],
  ["Argentina Science and Technology", "Government", "https://www.argentina.gob.ar/ciencia/noticias", "AR", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["CIPPEC Argentina", "ThinkTank", "https://www.cippec.org/", "AR", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Chile Government", "Government", "https://www.gob.cl/en/news/", "CL", "Latin America", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Chile", "Government", "https://www.bcentral.cl/en/web/banco-central/news", "CL", "Latin America", "en", "経済・金融", 87, "daily"],
  ["INE Chile", "Government", "https://www.ine.gob.cl/prensa", "CL", "Latin America", "es", "経済・金融", 84, "weekly"],
  ["Chile Ministry of Science", "Government", "https://www.minciencia.gob.cl/noticias/", "CL", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["Centro de Estudios Publicos Chile", "ThinkTank", "https://www.cepchile.cl/", "CL", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Colombia Presidency", "Government", "https://petro.presidencia.gov.co/prensa/Paginas/default.aspx", "CO", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Banco de la Republica Colombia", "Government", "https://www.banrep.gov.co/en/news", "CO", "Latin America", "en", "経済・金融", 87, "daily"],
  ["DANE Colombia", "Government", "https://www.dane.gov.co/index.php/en/press-releases", "CO", "Latin America", "en", "経済・金融", 84, "weekly"],
  ["Colombia Ministry of ICT", "Government", "https://www.mintic.gov.co/portal/inicio/Sala-de-prensa/Noticias/", "CO", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["Fedesarrollo Colombia", "ThinkTank", "https://www.fedesarrollo.org.co/", "CO", "Latin America", "es", "思想・社会", 83, "weekly"]
];

const additionalTechnologySources: SourceSeed[] = [
  ["Apple Machine Learning Research", "Website", "https://machinelearning.apple.com/", "US", "Global", "en", "テクノロジー", 86, "weekly"],
  ["Amazon Science", "Website", "https://www.amazon.science/blog", "US", "Global", "en", "テクノロジー", 86, "daily"],
  ["AWS Machine Learning Blog", "Website", "https://aws.amazon.com/blogs/machine-learning/", "US", "Global", "en", "テクノロジー", 85, "daily"],
  ["IBM Research Blog", "Website", "https://research.ibm.com/blog", "US", "Global", "en", "テクノロジー", 86, "weekly"],
  ["Salesforce AI Research", "Website", "https://www.salesforceairesearch.com/blog", "US", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Hugging Face Blog", "Website", "https://huggingface.co/blog", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["Cohere Blog", "Website", "https://cohere.com/blog", "CA", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Mistral AI News", "Website", "https://mistral.ai/news/", "FR", "Europe", "en", "テクノロジー", 84, "weekly"],
  ["xAI News", "Website", "https://x.ai/news", "US", "Global", "en", "テクノロジー", 83, "weekly"],
  ["Perplexity Blog", "Website", "https://www.perplexity.ai/hub/blog", "US", "Global", "en", "テクノロジー", 82, "weekly"],
  ["Stability AI News", "Website", "https://stability.ai/news", "UK", "Global", "en", "テクノロジー", 82, "weekly"],
  ["Databricks Blog", "Website", "https://www.databricks.com/blog", "US", "Global", "en", "テクノロジー", 83, "daily"],
  ["Snowflake Blog", "Website", "https://www.snowflake.com/blog/", "US", "Global", "en", "テクノロジー", 82, "weekly"],
  ["Cloudflare Blog", "Website", "https://blog.cloudflare.com/", "US", "Global", "en", "テクノロジー", 83, "daily"],
  ["GitHub Blog", "Website", "https://github.blog/", "US", "Global", "en", "テクノロジー", 83, "daily"],
  ["GitLab Blog", "Website", "https://about.gitlab.com/blog/", "US", "Global", "en", "テクノロジー", 82, "weekly"],
  ["Kubernetes Blog", "Website", "https://kubernetes.io/blog/", "Global", "Global", "en", "テクノロジー", 84, "weekly"],
  ["CNCF Blog", "Website", "https://www.cncf.io/blog/", "Global", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Linux Foundation News", "Website", "https://www.linuxfoundation.org/press", "Global", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Apache Software Foundation Blog", "Website", "https://blogs.apache.org/", "Global", "Global", "en", "テクノロジー", 83, "weekly"],
  ["Mozilla Blog", "Website", "https://blog.mozilla.org/en/", "US", "Global", "en", "テクノロジー", 82, "weekly"],
  ["W3C News", "InternationalOrganization", "https://www.w3.org/news/", "Global", "Global", "en", "テクノロジー", 87, "weekly"],
  ["IETF Blog", "InternationalOrganization", "https://www.ietf.org/blog/", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["ISO News", "InternationalOrganization", "https://www.iso.org/news.html", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["ITU News", "InternationalOrganization", "https://www.itu.int/en/mediacentre/Pages/default.aspx", "Global", "Global", "en", "テクノロジー", 87, "weekly"],
  ["GSMA Newsroom", "ThinkTank", "https://www.gsma.com/newsroom/", "Global", "Global", "en", "テクノロジー", 82, "weekly"],
  ["ICANN Announcements", "InternationalOrganization", "https://www.icann.org/en/announcements", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["CISA News", "Government", "https://www.cisa.gov/news-events/news", "US", "North America", "en", "テクノロジー", 90, "daily"],
  ["ENISA News", "Government", "https://www.enisa.europa.eu/news", "EU", "Europe", "en", "テクノロジー", 88, "weekly"],
  ["CERT Coordination Center", "Academic", "https://www.kb.cert.org/vuls/", "US", "North America", "en", "テクノロジー", 88, "daily"],
  ["JPCERT/CC", "Government", "https://www.jpcert.or.jp/english/", "JP", "Asia", "en", "テクノロジー", 88, "weekly"],
  ["UK National Cyber Security Centre", "Government", "https://www.ncsc.gov.uk/section/keep-up-to-date/news", "UK", "Europe", "en", "テクノロジー", 89, "weekly"],
  ["Cyber Security Agency of Singapore", "Government", "https://www.csa.gov.sg/news-events/news", "SG", "Southeast Asia", "en", "テクノロジー", 87, "weekly"],
  ["BSI Germany Cybersecurity", "Government", "https://www.bsi.bund.de/EN/Service-Navi/Press/press_node.html", "DE", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["ANSSI France", "Government", "https://cyber.gouv.fr/en/news", "FR", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["European Commission Digital Strategy", "Government", "https://digital-strategy.ec.europa.eu/en/news", "EU", "Europe", "en", "テクノロジー", 89, "daily"],
  ["Chips Joint Undertaking", "InternationalOrganization", "https://www.chips-ju.europa.eu/News/", "EU", "Europe", "en", "テクノロジー", 85, "weekly"],
  ["SEMI News", "ThinkTank", "https://www.semi.org/en/news-resources", "Global", "Global", "en", "テクノロジー", 82, "weekly"],
  ["Samsung Semiconductor Newsroom", "Website", "https://semiconductor.samsung.com/newsroom/", "KR", "Asia", "en", "テクノロジー", 84, "weekly"],
  ["SK hynix Newsroom", "Website", "https://news.skhynix.com/", "KR", "Asia", "en", "テクノロジー", 83, "weekly"],
  ["Micron Newsroom", "Website", "https://investors.micron.com/news-releases", "US", "Global", "en", "テクノロジー", 83, "weekly"],
  ["Qualcomm Newsroom", "Website", "https://www.qualcomm.com/news", "US", "Global", "en", "テクノロジー", 83, "weekly"],
  ["Arm Newsroom", "Website", "https://newsroom.arm.com/", "UK", "Global", "en", "テクノロジー", 83, "weekly"],
  ["MediaTek News", "Website", "https://corp.mediatek.com/news-events/press-releases", "TW", "Asia", "en", "テクノロジー", 82, "weekly"],
  ["Sony Semiconductor Solutions News", "Website", "https://www.sony-semicon.com/en/news/", "JP", "Asia", "en", "テクノロジー", 83, "weekly"],
  ["Toyota Research Institute", "Website", "https://www.tri.global/news", "US", "Global", "en", "テクノロジー", 83, "weekly"],
  ["NASA Technology News", "Government", "https://www.nasa.gov/technology/", "US", "North America", "en", "テクノロジー", 86, "weekly"],
  ["European Space Agency Technology", "InternationalOrganization", "https://www.esa.int/Enabling_Support/Space_Engineering_Technology", "EU", "Europe", "en", "テクノロジー", 85, "weekly"],
  ["JAXA News", "Government", "https://global.jaxa.jp/press/", "JP", "Asia", "en", "テクノロジー", 86, "weekly"],
  ["DLR News", "Government", "https://www.dlr.de/en/latest/news", "DE", "Europe", "en", "テクノロジー", 85, "weekly"],
  ["Max Planck Institute for Informatics", "Academic", "https://www.mpi-inf.mpg.de/news", "DE", "Europe", "en", "テクノロジー", 85, "weekly"],
  ["Center for Security and Emerging Technology", "ThinkTank", "https://cset.georgetown.edu/news/", "US", "Global", "en", "テクノロジー", 86, "weekly"],
  ["Ada Lovelace Institute", "ThinkTank", "https://www.adalovelaceinstitute.org/news/", "UK", "Global", "en", "テクノロジー", 84, "weekly"],
  ["AI Now Institute", "ThinkTank", "https://ainowinstitute.org/news", "US", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Partnership on AI", "ThinkTank", "https://partnershiponai.org/news/", "Global", "Global", "en", "テクノロジー", 84, "weekly"],
  ["Future of Life Institute", "ThinkTank", "https://futureoflife.org/news/", "Global", "Global", "en", "テクノロジー", 83, "weekly"],
  ["OECD Science Technology and Innovation", "InternationalOrganization", "https://www.oecd.org/sti/", "Global", "Global", "en", "テクノロジー", 88, "weekly"],
  ["WIPO Technology Trends", "InternationalOrganization", "https://www.wipo.int/web-publications/technology-trends/en/", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["World Bank Digital Development", "InternationalOrganization", "https://www.worldbank.org/en/topic/digitaldevelopment", "Global", "Global", "en", "テクノロジー", 88, "weekly"]
];

type CountryAmplificationRow = {
  name: string;
  code: string;
  region: string;
  language: string;
  political: [string, string];
  economic: [string, string, string];
  thought: [string, string];
};

const countryAmplificationRows: CountryAmplificationRow[] = [
  { name: "United States", code: "US", region: "North America", language: "en", political: ["https://www.usa.gov/branches-of-government", "https://www.congress.gov/news"], economic: ["https://home.treasury.gov/news/press-releases", "https://www.bea.gov/news", "https://www.federalreserve.gov/newsevents.htm"], thought: ["https://www.ed.gov/news", "https://www.dol.gov/newsroom/releases"] },
  { name: "Canada", code: "CA", region: "North America", language: "en", political: ["https://www.canada.ca/en/news.html", "https://www.ourcommons.ca/en/news"], economic: ["https://www.canada.ca/en/department-finance/news.html", "https://www.statcan.gc.ca/en/dai", "https://www.bankofcanada.ca/press/"], thought: ["https://www.canada.ca/en/employment-social-development/news.html", "https://www.canada.ca/en/services/culture.html"] },
  { name: "Mexico", code: "MX", region: "Latin America", language: "es", political: ["https://www.gob.mx/presidencia/prensa", "https://comunicacionsocial.diputados.gob.mx/"], economic: ["https://www.gob.mx/shcp/prensa", "https://www.inegi.org.mx/app/saladeprensa/", "https://www.banxico.org.mx/publicaciones-y-prensa/"], thought: ["https://www.gob.mx/sep/prensa", "https://www.gob.mx/stps/prensa"] },
  { name: "Brazil", code: "BR", region: "South America", language: "pt", political: ["https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/noticias", "https://www.camara.leg.br/noticias/"], economic: ["https://www.gov.br/fazenda/pt-br/assuntos/noticias", "https://agenciadenoticias.ibge.gov.br/", "https://www.bcb.gov.br/detalhenoticia/ultimas"], thought: ["https://www.gov.br/mec/pt-br/assuntos/noticias", "https://www.gov.br/trabalho-e-emprego/pt-br/noticias-e-conteudo"] },
  { name: "Argentina", code: "AR", region: "Latin America", language: "es", political: ["https://www.argentina.gob.ar/noticias", "https://www.hcdn.gob.ar/prensa/index.html"], economic: ["https://www.argentina.gob.ar/economia/noticias", "https://www.indec.gob.ar/indec/web/Institucional-Indec-Noticias", "https://www.bcra.gob.ar/Noticias/"], thought: ["https://www.argentina.gob.ar/educacion/noticias", "https://www.argentina.gob.ar/trabajo/noticias"] },
  { name: "Chile", code: "CL", region: "Latin America", language: "es", political: ["https://www.gob.cl/noticias/", "https://www.camara.cl/cms/noticias/"], economic: ["https://www.hacienda.cl/noticias-y-eventos", "https://www.ine.gob.cl/prensa", "https://www.bcentral.cl/web/banco-central/noticias"], thought: ["https://www.mineduc.cl/noticias/", "https://www.mintrab.gob.cl/noticias/"] },
  { name: "Colombia", code: "CO", region: "Latin America", language: "es", political: ["https://petro.presidencia.gov.co/prensa/Paginas/default.aspx", "https://www.camara.gov.co/noticias"], economic: ["https://www.minhacienda.gov.co/webcenter/portal/Minhacienda/pages_prensa", "https://www.dane.gov.co/index.php/actualidad-dane", "https://www.banrep.gov.co/es/noticias"], thought: ["https://www.mineducacion.gov.co/portal/salaprensa/Noticias/", "https://www.mintrabajo.gov.co/prensa/comunicados"] },
  { name: "Peru", code: "PE", region: "Latin America", language: "es", political: ["https://www.gob.pe/presidencia", "https://comunicaciones.congreso.gob.pe/noticias/"], economic: ["https://www.gob.pe/mef", "https://www.inei.gob.pe/prensa/noticias/", "https://www.bcrp.gob.pe/notas-de-prensa.html"], thought: ["https://www.gob.pe/minedu", "https://www.gob.pe/mtpe"] },
  { name: "United Kingdom", code: "UK", region: "Europe", language: "en", political: ["https://www.gov.uk/search/news-and-communications", "https://www.parliament.uk/business/news/"], economic: ["https://www.gov.uk/government/organisations/hm-treasury", "https://www.ons.gov.uk/news", "https://www.bankofengland.co.uk/news"], thought: ["https://www.gov.uk/government/organisations/department-for-education", "https://www.gov.uk/government/organisations/department-for-work-pensions"] },
  { name: "Ireland", code: "IE", region: "Europe", language: "en", political: ["https://www.gov.ie/en/news/", "https://www.oireachtas.ie/en/press-centre/"], economic: ["https://www.gov.ie/en/organisation/department-of-finance/", "https://www.cso.ie/en/releasesandpublications/", "https://www.centralbank.ie/news-media/press-releases"], thought: ["https://www.gov.ie/en/organisation/department-of-education/", "https://www.gov.ie/en/organisation/department-of-social-protection/"] },
  { name: "France", code: "FR", region: "Europe", language: "fr", political: ["https://www.gouvernement.fr/actualite", "https://www.assemblee-nationale.fr/dyn/actualites-accueil"], economic: ["https://www.economie.gouv.fr/actualites", "https://www.insee.fr/fr/actualites", "https://www.banque-france.fr/fr/communiques-de-presse"], thought: ["https://www.education.gouv.fr/actualites", "https://travail-emploi.gouv.fr/actualites"] },
  { name: "Germany", code: "DE", region: "Europe", language: "de", political: ["https://www.bundesregierung.de/breg-de/aktuelles", "https://www.bundestag.de/presse"], economic: ["https://www.bundesfinanzministerium.de/Web/DE/Presse/presse.html", "https://www.destatis.de/DE/Presse/Pressemitteilungen/_inhalt.html", "https://www.bundesbank.de/de/presse"], thought: ["https://www.bmbf.de/DE/Service/Presse/presse_node.html", "https://www.bmas.de/DE/Service/Presse/Pressemitteilungen/pressemitteilungen.html"] },
  { name: "Italy", code: "IT", region: "Europe", language: "it", political: ["https://www.governo.it/it/notizie", "https://www.camera.it/leg19/1132"], economic: ["https://www.mef.gov.it/ufficio-stampa/comunicati/", "https://www.istat.it/it/archivio/comunicati+stampa", "https://www.bancaditalia.it/media/notizia/"], thought: ["https://www.mim.gov.it/web/guest/news", "https://www.lavoro.gov.it/notizie"] },
  { name: "Spain", code: "ES", region: "Europe", language: "es", political: ["https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/Paginas/index.aspx", "https://www.congreso.es/es/notas-de-prensa"], economic: ["https://portal.mineco.gob.es/es-es/comunicacion/Paginas/notas-prensa.aspx", "https://www.ine.es/prensa/prensa.htm", "https://www.bde.es/wbe/es/noticias-eventos/"], thought: ["https://www.educacionfpydeportes.gob.es/prensa.html", "https://www.mites.gob.es/es/prensa/"] },
  { name: "Netherlands", code: "NL", region: "Europe", language: "en", political: ["https://www.government.nl/latest/news", "https://www.houseofrepresentatives.nl/news"], economic: ["https://www.government.nl/ministries/ministry-of-finance/news", "https://www.cbs.nl/en-gb/news", "https://www.dnb.nl/en/general-news/"], thought: ["https://www.government.nl/ministries/ministry-of-education-culture-and-science/news", "https://www.government.nl/ministries/ministry-of-social-affairs-and-employment/news"] },
  { name: "Sweden", code: "SE", region: "Europe", language: "en", political: ["https://www.government.se/press-releases/", "https://www.riksdagen.se/en/news/"], economic: ["https://www.government.se/government-of-sweden/ministry-of-finance/", "https://www.scb.se/en/About-us/news-and-press-releases/", "https://www.riksbank.se/en-gb/press-and-published/notices-and-press-releases/"], thought: ["https://www.government.se/government-of-sweden/ministry-of-education-and-research/", "https://www.government.se/government-of-sweden/ministry-of-health-and-social-affairs/"] },
  { name: "Norway", code: "NO", region: "Europe", language: "en", political: ["https://www.regjeringen.no/en/whatsnew/id2006120/", "https://www.stortinget.no/en/In-English/About-the-Storting/News-archive/"], economic: ["https://www.regjeringen.no/en/dep/fin/id216/", "https://www.ssb.no/en", "https://www.norges-bank.no/en/news-events/"], thought: ["https://www.regjeringen.no/en/dep/kd/id586/", "https://www.regjeringen.no/en/dep/aid/id165/"] },
  { name: "Denmark", code: "DK", region: "Europe", language: "en", political: ["https://www.thedanishparliament.dk/en/news", "https://english.stm.dk/news/"], economic: ["https://en.fm.dk/news/", "https://www.dst.dk/en/presse", "https://www.nationalbanken.dk/en/news-and-knowledge/press"], thought: ["https://eng.uvm.dk/news", "https://bm.dk/news/"] },
  { name: "Switzerland", code: "CH", region: "Europe", language: "en", political: ["https://www.admin.ch/gov/en/start/documentation/media-releases.html", "https://www.parlament.ch/en/services/news"], economic: ["https://www.efd.admin.ch/efd/en/home/the-fdf/nsb-news_list.msg-id-*.html", "https://www.bfs.admin.ch/bfs/en/home/news.html", "https://www.snb.ch/en/publications/communication/press-releases"], thought: ["https://www.sbfi.admin.ch/sbfi/en/home/services/news.html", "https://www.bsv.admin.ch/bsv/en/home/publications-and-services/medieninformationen.html"] },
  { name: "Poland", code: "PL", region: "Europe", language: "en", political: ["https://www.gov.pl/web/primeminister/news", "https://www.sejm.gov.pl/Sejm10.nsf/news.xsp"], economic: ["https://www.gov.pl/web/finance/news", "https://stat.gov.pl/en/news/", "https://nbp.pl/en/news/"], thought: ["https://www.gov.pl/web/education/news", "https://www.gov.pl/web/family/news"] },
  { name: "Turkey", code: "TR", region: "Middle East", language: "en", political: ["https://www.tccb.gov.tr/en/news/", "https://www.tbmm.gov.tr/Haber"], economic: ["https://en.hmb.gov.tr/announcements", "https://data.tuik.gov.tr/Bulten/Index", "https://www.tcmb.gov.tr/wps/wcm/connect/en/tcmb+en/main+menu/announcements/press+releases"], thought: ["https://www.meb.gov.tr/en/", "https://www.csgb.gov.tr/en/"] },
  { name: "Israel", code: "IL", region: "Middle East", language: "en", political: ["https://www.gov.il/en/departments/news", "https://main.knesset.gov.il/en/news/pressreleases/pages/default.aspx"], economic: ["https://www.gov.il/en/departments/news?OfficeId=104cb0f4-d65a-4692-b590-94af928c19c0", "https://www.cbs.gov.il/en/mediarelease/pages/default.aspx", "https://www.boi.org.il/en/communication-and-publications/press-releases/"], thought: ["https://www.gov.il/en/departments/ministry_of_education/news", "https://www.gov.il/en/departments/ministry_of_labor/news"] },
  { name: "United Arab Emirates", code: "AE", region: "Middle East", language: "en", political: ["https://u.ae/en/media/news", "https://www.mocaf.gov.ae/en/media-center/news"], economic: ["https://mof.gov.ae/media-centre/news/", "https://fcsc.gov.ae/en-us/Pages/News.aspx", "https://www.centralbank.ae/en/news-and-media/"], thought: ["https://www.moe.gov.ae/En/MediaCenter/News/Pages/default.aspx", "https://www.mohre.gov.ae/en/media-centre/news.aspx"] },
  { name: "Saudi Arabia", code: "SA", region: "Middle East", language: "en", political: ["https://www.spa.gov.sa/en", "https://www.shura.gov.sa/wps/wcm/connect/ShuraEn/internet/News/"], economic: ["https://www.mof.gov.sa/en/MediaCenter/news/Pages/default.aspx", "https://www.stats.gov.sa/en/news", "https://www.sama.gov.sa/en-US/News/Pages/default.aspx"], thought: ["https://www.moe.gov.sa/en/mediacenter/news/Pages/default.aspx", "https://hrsd.gov.sa/en/media-center/news"] },
  { name: "India", code: "IN", region: "Asia", language: "en", political: ["https://www.pmindia.gov.in/en/news_updates/", "https://sansad.in/ls/news"], economic: ["https://dea.gov.in/news", "https://www.mospi.gov.in/press-release", "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx"], thought: ["https://www.education.gov.in/press-releases", "https://labour.gov.in/whatsnew"] },
  { name: "China", code: "CN", region: "Asia", language: "en", political: ["https://english.www.gov.cn/news/", "http://www.npc.gov.cn/englishnpc/index.shtml"], economic: ["https://english.www.gov.cn/statecouncil/ministries/202006/24/content_WS5ef34f2fc6d05a0f89706bf5.html", "https://www.stats.gov.cn/english/PressRelease/", "http://www.pbc.gov.cn/en/3688110/3688172/index.html"], thought: ["http://en.moe.gov.cn/news/press_releases/", "http://english.www.gov.cn/statecouncil/ministries/202006/24/content_WS5ef34f1fc6d05a0f89706bf0.html"] },
  { name: "Japan", code: "JP", region: "Asia", language: "ja", political: ["https://www.kantei.go.jp/jp/tyoukanpress/", "https://www.shugiin.go.jp/internet/itdb_annai.nsf/html/statics/topics.htm"], economic: ["https://www.mof.go.jp/public_relations/news/index.htm", "https://www.stat.go.jp/info/news/index.html", "https://www.boj.or.jp/about/press/index.htm"], thought: ["https://www.mext.go.jp/b_menu/houdou/index.htm", "https://www.mhlw.go.jp/stf/houdou/index.html"] },
  { name: "South Korea", code: "KR", region: "Asia", language: "en", political: ["https://www.korea.net/Government/Briefing-Room/Press-Releases", "https://korea.assembly.go.kr:447/portalEng/bbs/B0000144/list.do"], economic: ["https://english.moef.go.kr/pc/selectTbPressCenterList.do", "https://kostat.go.kr/anse/", "https://www.bok.or.kr/eng/bbs/E0000634/list.do"], thought: ["https://english.moe.go.kr/boardCnts/listRenewal.do?boardID=265", "https://www.moel.go.kr/english/poli/poliNewsnews.jsp"] },
  { name: "Taiwan", code: "TW", region: "Asia", language: "en", political: ["https://english.ey.gov.tw/News3", "https://www.ly.gov.tw/EngPages/List.aspx?nodeid=43534"], economic: ["https://www.mof.gov.tw/Eng/news.aspx", "https://eng.stat.gov.tw/News.aspx?n=1576", "https://www.cbc.gov.tw/en/lp-2-2.html"], thought: ["https://english.moe.gov.tw/lp-117-1.html", "https://english.mol.gov.tw/21139/21156/"] },
  { name: "Singapore", code: "SG", region: "Southeast Asia", language: "en", political: ["https://www.gov.sg/news", "https://www.parliament.gov.sg/newsroom"], economic: ["https://www.mof.gov.sg/news-publications/press-releases", "https://www.singstat.gov.sg/whats-new/latest-news", "https://www.mas.gov.sg/news"], thought: ["https://www.moe.gov.sg/news", "https://www.mom.gov.sg/newsroom"] },
  { name: "Indonesia", code: "ID", region: "Southeast Asia", language: "en", political: ["https://setkab.go.id/en/category/news/", "https://www.dpr.go.id/en/berita"], economic: ["https://fiskal.kemenkeu.go.id/publikasi/siaran-pers", "https://www.bps.go.id/en/pressrelease", "https://www.bi.go.id/en/publikasi/ruang-media/news-release/Default.aspx"], thought: ["https://www.kemdikbud.go.id/main/blog", "https://kemnaker.go.id/news"] },
  { name: "Vietnam", code: "VN", region: "Southeast Asia", language: "en", political: ["https://en.baochinhphu.vn/", "https://quochoi.vn/hoatdongdbqh/Pages/tin-hoat-dong-dai-bieu.aspx"], economic: ["https://mof.gov.vn/webcenter/portal/mof/en", "https://www.gso.gov.vn/en/data-and-statistics/", "https://www.sbv.gov.vn/webcenter/portal/en/home/sbv/news"], thought: ["https://moet.gov.vn/Pages/home.aspx", "https://www.molisa.gov.vn/baiviet/"] },
  { name: "Thailand", code: "TH", region: "Southeast Asia", language: "en", political: ["https://thailand.prd.go.th/en", "https://www.parliament.go.th/ewtadmin/ewt/parliament_en/main.php?filename=index"], economic: ["https://www.mof.go.th/en/news", "https://www.nso.go.th/nsoweb/index?set_lang=en", "https://www.bot.or.th/en/news-and-media/news.html"], thought: ["https://www.moe.go.th/", "https://www.mol.go.th/en/news/"] },
  { name: "Malaysia", code: "MY", region: "Southeast Asia", language: "en", political: ["https://www.pmo.gov.my/news/", "https://www.parlimen.gov.my/news.html?uweb=web&lang=en"], economic: ["https://www.mof.gov.my/portal/en/news/press-citations", "https://www.dosm.gov.my/portal-main/release-content", "https://www.bnm.gov.my/press-releases"], thought: ["https://www.moe.gov.my/en/pemberitahuan/announcement", "https://www.mohr.gov.my/index.php/en/news"] },
  { name: "Philippines", code: "PH", region: "Southeast Asia", language: "en", political: ["https://www.officialgazette.gov.ph/", "https://www.congress.gov.ph/media/press/"], economic: ["https://www.dof.gov.ph/category/news/", "https://psa.gov.ph/statistics/press-releases", "https://www.bsp.gov.ph/SitePages/MediaAndResearch/MediaList.aspx"], thought: ["https://www.deped.gov.ph/category/news/", "https://www.dole.gov.ph/news/"] },
  { name: "Australia", code: "AU", region: "Oceania", language: "en", political: ["https://www.pm.gov.au/media", "https://www.aph.gov.au/About_Parliament/News_and_Events"], economic: ["https://ministers.treasury.gov.au/", "https://www.abs.gov.au/media-centre", "https://www.rba.gov.au/media-releases/"], thought: ["https://www.education.gov.au/newsroom", "https://www.dewr.gov.au/newsroom"] },
  { name: "New Zealand", code: "NZ", region: "Oceania", language: "en", political: ["https://www.beehive.govt.nz/", "https://www.parliament.nz/en/get-involved/features/"], economic: ["https://www.treasury.govt.nz/news-and-events/news", "https://www.stats.govt.nz/news/", "https://www.rbnz.govt.nz/hub/news"], thought: ["https://www.education.govt.nz/news/", "https://www.msd.govt.nz/about-msd-and-our-work/newsroom/"] },
  { name: "South Africa", code: "ZA", region: "Africa", language: "en", political: ["https://www.thepresidency.gov.za/press-statements", "https://www.parliament.gov.za/news"], economic: ["https://www.treasury.gov.za/comm_media/press/default.aspx", "https://www.statssa.gov.za/?page_id=1854", "https://www.resbank.co.za/en/home/publications/publication-detail-pages/media-releases"], thought: ["https://www.education.gov.za/Newsroom.aspx", "https://www.labour.gov.za/media-desk/media-alerts"] },
  { name: "Nigeria", code: "NG", region: "Africa", language: "en", political: ["https://statehouse.gov.ng/news/", "https://nass.gov.ng/news"], economic: ["https://finance.gov.ng/news/", "https://www.nigerianstat.gov.ng/news", "https://www.cbn.gov.ng/Out/News.asp"], thought: ["https://education.gov.ng/news/", "https://labour.gov.ng/news/"] },
  { name: "Kenya", code: "KE", region: "Africa", language: "en", political: ["https://www.president.go.ke/news/", "http://www.parliament.go.ke/news-events"], economic: ["https://www.treasury.go.ke/news-updates/", "https://www.knbs.or.ke/news/", "https://www.centralbank.go.ke/media-center/"], thought: ["https://www.education.go.ke/news", "https://www.labour.go.ke/news"] },
  { name: "Egypt", code: "EG", region: "Africa", language: "en", political: ["https://www.sis.gov.eg/section/0/501?lang=en-us", "https://www.parliament.gov.eg/"], economic: ["https://mof.gov.eg/en/posts/news", "https://www.capmas.gov.eg/HomePage.aspx?lang=2", "https://www.cbe.org.eg/en/news-publications/news"], thought: ["https://moe.gov.eg/en/what-s-on/news/", "https://www.manpower.gov.eg/"] },
  { name: "Morocco", code: "MA", region: "Africa", language: "fr", political: ["https://www.cg.gov.ma/fr/actualites", "https://www.chambredesrepresentants.ma/fr/actualites"], economic: ["https://www.finances.gov.ma/fr/Pages/Actualites.aspx", "https://www.hcp.ma/Communiques-de-presse_r18.html", "https://www.bkam.ma/Communiques"], thought: ["https://www.men.gov.ma/Fr/Pages/Accueil.aspx", "https://www.travail.gov.ma/"] },
  { name: "Ghana", code: "GH", region: "Africa", language: "en", political: ["https://presidency.gov.gh/index.php/briefing-room/news-style-2", "https://www.parliament.gh/news"], economic: ["https://mofep.gov.gh/news-and-events", "https://statsghana.gov.gh/gssmain/pressrelease", "https://www.bog.gov.gh/news/"], thought: ["https://moe.gov.gh/category/news/", "https://www.melr.gov.gh/news/"] },
  { name: "Ethiopia", code: "ET", region: "Africa", language: "en", political: ["https://www.pmo.gov.et/news/", "https://www.hopr.gov.et/"], economic: ["https://www.mofed.gov.et/", "https://www.statsethiopia.gov.et/news/", "https://nbe.gov.et/news/"], thought: ["https://www.moe.gov.et/", "https://www.mols.gov.et/"] },
  { name: "Rwanda", code: "RW", region: "Africa", language: "en", political: ["https://www.gov.rw/news", "https://www.parliament.gov.rw/news-detail"], economic: ["https://www.minecofin.gov.rw/news", "https://www.statistics.gov.rw/news", "https://www.bnr.rw/news-publications/news/"], thought: ["https://www.mineduc.gov.rw/news", "https://www.mifotra.gov.rw/news-detail"] },
  { name: "European Union", code: "EU", region: "Europe", language: "en", political: ["https://ec.europa.eu/commission/presscorner/home/en", "https://www.europarl.europa.eu/news/en/press-room"], economic: ["https://economy-finance.ec.europa.eu/news_en", "https://ec.europa.eu/eurostat/web/main/news", "https://www.ecb.europa.eu/press/html/index.en.html"], thought: ["https://education.ec.europa.eu/news", "https://employment-social-affairs.ec.europa.eu/news_en"] },
  { name: "African Union", code: "AU", region: "Africa", language: "en", political: ["https://au.int/en/news", "https://pap.au.int/en/news"], economic: ["https://au.int/en/pressreleases", "https://au.int/en/directorates/economic-development-integration-and-trade", "https://www.afdb.org/en/news-and-events"], thought: ["https://au.int/en/education-science-technology-innovation", "https://au.int/en/social-affairs"] },
  { name: "ASEAN", code: "ASEAN", region: "Southeast Asia", language: "en", political: ["https://asean.org/category/news/", "https://asean.org/asean2020/category/statements/"], economic: ["https://asean.org/our-communities/economic-community/", "https://aseanstats.org/news-events/", "https://asean.org/category/press-releases/"], thought: ["https://asean.org/our-communities/socio-cultural-community/", "https://asean.org/category/news/asean-socio-cultural-community/"] },
  { name: "OECD", code: "OECD", region: "Global", language: "en", political: ["https://www.oecd.org/newsroom/", "https://www.oecd.org/governance/"], economic: ["https://www.oecd.org/economy/", "https://www.oecd.org/statistics/", "https://www.oecd.org/finance/"], thought: ["https://www.oecd.org/education/", "https://www.oecd.org/employment/"] },
  { name: "United Nations", code: "UN", region: "Global", language: "en", political: ["https://news.un.org/en/", "https://press.un.org/en"], economic: ["https://unctad.org/news", "https://unstats.un.org/UNSDWebsite/news/", "https://www.un.org/development/desa/en/news.html"], thought: ["https://www.unesco.org/en/newsroom", "https://www.ilo.org/global/about-the-ilo/newsroom/news/lang--en/index.htm"] },
  { name: "World Bank Group", code: "WBG", region: "Global", language: "en", political: ["https://www.worldbank.org/en/news/all", "https://ieg.worldbankgroup.org/news"], economic: ["https://www.worldbank.org/en/news/all?topic_exact=Macroeconomics", "https://data.worldbank.org/news", "https://www.worldbank.org/en/topic/financialsector"], thought: ["https://www.worldbank.org/en/topic/education", "https://www.worldbank.org/en/topic/socialprotection"] },
  { name: "International Monetary Fund", code: "IMF", region: "Global", language: "en", political: ["https://www.imf.org/en/News", "https://www.imf.org/en/News/Seminars"], economic: ["https://www.imf.org/en/News/Articles", "https://www.imf.org/en/Data", "https://www.imf.org/en/Publications"], thought: ["https://www.imf.org/en/Topics/inequality", "https://www.imf.org/en/Topics/jobs-and-growth"] },
  { name: "World Trade Organization", code: "WTO", region: "Global", language: "en", political: ["https://www.wto.org/english/news_e/news_e.htm", "https://www.wto.org/english/thewto_e/minist_e/minist_e.htm"], economic: ["https://www.wto.org/english/res_e/statis_e/statis_e.htm", "https://www.wto.org/english/news_e/pres_e/pres_e.htm", "https://www.wto.org/english/tratop_e/tratop_e.htm"], thought: ["https://www.wto.org/english/res_e/reser_e/reser_e.htm", "https://www.wto.org/english/tratop_e/devel_e/devel_e.htm"] },
  { name: "G20", code: "G20", region: "Global", language: "en", political: ["https://www.g20.org/en/news/", "https://www.g20.org/en/documents/"], economic: ["https://www.g20.org/en/workstreams/finance-track/", "https://www.g20.org/en/statistics/", "https://www.fsb.org/news/"], thought: ["https://www.g20.org/en/workstreams/sherpa-track/", "https://www.g20.org/en/workstreams/education/"] },
  { name: "Nordic Council", code: "NORDIC", region: "Europe", language: "en", political: ["https://www.norden.org/en/news", "https://www.norden.org/en/organisation/nordic-council"], economic: ["https://www.norden.org/en/information/economy", "https://www.nordicstatistics.org/news/", "https://www.nib.int/who_we_are/news_and_media"], thought: ["https://www.norden.org/en/information/education-and-research", "https://www.norden.org/en/information/welfare"] },
  { name: "Pacific Islands Forum", code: "PIF", region: "Oceania", language: "en", political: ["https://forumsec.org/news", "https://forumsec.org/publications"], economic: ["https://forumsec.org/economic-governance", "https://spccfpstore1.blob.core.windows.net/digitallibrary-docs/files/ab/ab0f0b67229ca4a63eb4d2a8d76664f4.pdf", "https://www.adb.org/news"], thought: ["https://forumsec.org/social-policy", "https://forumsec.org/human-security"] },
  { name: "Caribbean Community", code: "CARICOM", region: "Latin America", language: "en", political: ["https://caricom.org/media-center/communications/news/", "https://caricom.org/documents/"], economic: ["https://caricom.org/our-work/economic-integration-innovation-and-development/", "https://statistics.caricom.org/", "https://www.caribank.org/newsroom/news-and-events"], thought: ["https://caricom.org/our-work/human-and-social-development/", "https://caricom.org/our-work/social-development/"] },
  { name: "Mercosur", code: "MERCOSUR", region: "Latin America", language: "es", political: ["https://www.mercosur.int/noticias/", "https://www.parlamentomercosur.org/"], economic: ["https://www.mercosur.int/temas/economia/", "https://www.mercosur.int/documentos-y-normativa/", "https://www.mercosur.int/temas/comercio/"], thought: ["https://www.mercosur.int/temas/educacion/", "https://www.mercosur.int/temas/social/"] }
];

const politicalAmplificationSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Government Signal`, "Government", row.political[0], row.code, row.region, row.language, "政治・国際機関", 84, "weekly"],
  [`${row.name} Parliamentary Signal`, "Government", row.political[1], row.code, row.region, row.language, "政治・国際機関", 83, "weekly"]
] as SourceSeed[]));

const economicAmplificationSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Fiscal Signal`, "Government", row.economic[0], row.code, row.region, row.language, "経済・金融", 84, "weekly"],
  [`${row.name} Statistics Signal`, "Government", row.economic[1], row.code, row.region, row.language, "経済・金融", 84, "weekly"],
  [`${row.name} Monetary Signal`, "Government", row.economic[2], row.code, row.region, row.language, "経済・金融", 84, "weekly"]
] as SourceSeed[]));

const thoughtAmplificationSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Education Signal`, "Government", row.thought[0], row.code, row.region, row.language, "思想・社会", 83, "weekly"],
  [`${row.name} Labor and Social Signal`, "Government", row.thought[1], row.code, row.region, row.language, "思想・社会", 83, "weekly"]
] as SourceSeed[]));

function focusedUrl(url: string, focus: string) {
  return `${url}${url.includes("#") ? "&" : "#"}si-${focus}`;
}

const politicalScaleSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Executive Agenda Watch`, "Government", focusedUrl(row.political[0], "executive-agenda"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"],
  [`${row.name} Legislative Agenda Watch`, "Government", focusedUrl(row.political[1], "legislative-agenda"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"],
  [`${row.name} Regulation Watch`, "Government", focusedUrl(row.political[0], "regulation"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"],
  [`${row.name} Foreign Policy Watch`, "Government", focusedUrl(row.political[0], "foreign-policy"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"],
  [`${row.name} Public Administration Watch`, "Government", focusedUrl(row.political[0], "public-administration"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"],
  [`${row.name} Institutional Risk Watch`, "Government", focusedUrl(row.political[1], "institutional-risk"), row.code, row.region, row.language, "政治・国際機関", 82, "weekly"]
] as SourceSeed[]));

const economicScaleSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Fiscal Policy Watch`, "Government", focusedUrl(row.economic[0], "fiscal-policy"), row.code, row.region, row.language, "経済・金融", 82, "weekly"],
  [`${row.name} Macro Statistics Watch`, "Government", focusedUrl(row.economic[1], "macro-statistics"), row.code, row.region, row.language, "経済・金融", 82, "weekly"],
  [`${row.name} Monetary Policy Watch`, "Government", focusedUrl(row.economic[2], "monetary-policy"), row.code, row.region, row.language, "経済・金融", 82, "weekly"],
  [`${row.name} Trade and Investment Watch`, "Government", focusedUrl(row.economic[0], "trade-investment"), row.code, row.region, row.language, "経済・金融", 82, "weekly"],
  [`${row.name} Labor Market Economy Watch`, "Government", focusedUrl(row.economic[1], "labor-market"), row.code, row.region, row.language, "経済・金融", 82, "weekly"]
] as SourceSeed[]));

const thoughtScaleSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} Education Reform Watch`, "Government", focusedUrl(row.thought[0], "education-reform"), row.code, row.region, row.language, "思想・社会", 81, "weekly"],
  [`${row.name} Work and Skills Watch`, "Government", focusedUrl(row.thought[1], "work-skills"), row.code, row.region, row.language, "思想・社会", 81, "weekly"],
  [`${row.name} Social Cohesion Watch`, "Government", focusedUrl(row.thought[1], "social-cohesion"), row.code, row.region, row.language, "思想・社会", 81, "weekly"],
  [`${row.name} Demography Watch`, "Government", focusedUrl(row.thought[1], "demography"), row.code, row.region, row.language, "思想・社会", 81, "weekly"],
  [`${row.name} Culture and Values Watch`, "Government", focusedUrl(row.thought[0], "culture-values"), row.code, row.region, row.language, "思想・社会", 81, "weekly"],
  [`${row.name} Inequality and Trust Watch`, "Government", focusedUrl(row.thought[1], "inequality-trust"), row.code, row.region, row.language, "思想・社会", 81, "weekly"]
] as SourceSeed[]));

const technologyScaleSources: SourceSeed[] = countryAmplificationRows.flatMap((row) => ([
  [`${row.name} AI Policy Watch`, "Government", focusedUrl(row.political[0], "ai-policy"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Digital Government Watch`, "Government", focusedUrl(row.political[0], "digital-government"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Cybersecurity Policy Watch`, "Government", focusedUrl(row.political[0], "cybersecurity-policy"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Research and Innovation Watch`, "Government", focusedUrl(row.thought[0], "research-innovation"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Digital Infrastructure Watch`, "Government", focusedUrl(row.economic[0], "digital-infrastructure"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Standards and Interoperability Watch`, "Government", focusedUrl(row.economic[1], "standards-interoperability"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"],
  [`${row.name} Innovation Ecosystem Watch`, "Government", focusedUrl(row.economic[2], "innovation-ecosystem"), row.code, row.region, row.language, "テクノロジー", 81, "weekly"]
] as SourceSeed[]));

export const initialSources: Source[] = [
  ...politicalSources,
  ...economicSources,
  ...thoughtSources,
  ...technologySources,
  ...countryLayerSources,
  ...emergingRegionSources,
  ...additionalTechnologySources,
  ...politicalAmplificationSources,
  ...economicAmplificationSources,
  ...thoughtAmplificationSources,
  ...politicalScaleSources,
  ...economicScaleSources,
  ...thoughtScaleSources,
  ...technologyScaleSources
].map(([name, source_type, url, country, region, language, category, reliability_score, crawl_frequency], index) => ({
  id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  name,
  source_type,
  url,
  country,
  region,
  language,
  category,
  reliability_score,
  crawl_frequency,
  is_active: true,
  created_at: now
} as Source));
