import type { CrawlFrequency, Source, SourceType } from "@/lib/types";

const now = new Date().toISOString();

type SourceSeed = [
  name: string,
  source_type: SourceType,
  url: string,
  country: string,
  region: string,
  language: string,
  category: string,
  reliability_score: number,
  crawl_frequency: CrawlFrequency
];

const politicalSources: SourceSeed[] = [
  ["White House", "Government", "https://www.whitehouse.gov/briefing-room/feed/", "US", "North America", "en", "政治・国際機関", 95, "hourly"],
  ["US State Department", "Government", "https://www.state.gov/rss-feed/", "US", "North America", "en", "政治・国際機関", 94, "every_6_hours"],
  ["Federal Register", "Government", "https://www.federalregister.gov/documents/search.rss", "US", "North America", "en", "政治・国際機関", 93, "daily"],
  ["Congress.gov", "Government", "https://www.congress.gov/", "US", "North America", "en", "政治・国際機関", 92, "daily"],
  ["Congressional Research Service", "Government", "https://crsreports.congress.gov/", "US", "North America", "en", "政治・国際機関", 91, "weekly"],
  ["European Commission", "InternationalOrganization", "https://ec.europa.eu/commission/presscorner/api/rss", "EU", "Europe", "en", "政治・国際機関", 93, "every_6_hours"],
  ["European Council", "InternationalOrganization", "https://www.consilium.europa.eu/en/press/press-releases/", "EU", "Europe", "en", "政治・国際機関", 92, "daily"],
  ["European Parliament News", "InternationalOrganization", "https://www.europarl.europa.eu/news/en/rss", "EU", "Europe", "en", "政治・国際機関", 90, "daily"],
  ["United Nations News", "InternationalOrganization", "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "Global", "Global", "en", "政治・国際機関", 94, "every_6_hours"],
  ["UN Secretary-General Statements", "InternationalOrganization", "https://www.un.org/sg/en/content/sg/statement", "Global", "Global", "en", "政治・国際機関", 91, "daily"],
  ["UNDP", "InternationalOrganization", "https://www.undp.org/news-centre", "Global", "Global", "en", "政治・国際機関", 89, "daily"],
  ["WHO News", "InternationalOrganization", "https://www.who.int/news", "Global", "Global", "en", "政治・国際機関", 91, "daily"],
  ["WTO News", "InternationalOrganization", "https://www.wto.org/english/news_e/news_e.htm", "Global", "Global", "en", "政治・国際機関", 90, "daily"],
  ["OECD News", "InternationalOrganization", "https://www.oecd.org/newsroom/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "政治・国際機関", 92, "daily"],
  ["World Economic Forum Agenda", "ThinkTank", "https://www.weforum.org/agenda/feed/", "Global", "Global", "en", "政治・国際機関", 86, "daily"],
  ["NATO News", "InternationalOrganization", "https://www.nato.int/cps/en/natohq/news.xml", "Global", "Europe", "en", "政治・国際機関", 91, "daily"],
  ["G7 Hiroshima Process / Cabinet Secretariat", "Government", "https://www.cas.go.jp/", "JP", "Asia", "ja", "政治・国際機関", 89, "weekly"],
  ["日本国外務省", "Government", "https://www.mofa.go.jp/mofaj/rss/index.xml", "JP", "Asia", "ja", "政治・国際機関", 94, "daily"],
  ["内閣府", "Government", "https://www.cao.go.jp/rss/news.xml", "JP", "Asia", "ja", "政治・国際機関", 92, "daily"],
  ["首相官邸", "Government", "https://www.kantei.go.jp/", "JP", "Asia", "ja", "政治・国際機関", 92, "daily"],
  ["総務省", "Government", "https://www.soumu.go.jp/menu_news/index.html", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["デジタル庁", "Government", "https://www.digital.go.jp/news", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["防衛省", "Government", "https://www.mod.go.jp/j/press/news/", "JP", "Asia", "ja", "政治・国際機関", 91, "daily"],
  ["CSIS", "ThinkTank", "https://www.csis.org/rss.xml", "US", "Global", "en", "政治・国際機関", 88, "daily"],
  ["RAND Corporation", "ThinkTank", "https://www.rand.org/pubs.xml", "US", "Global", "en", "政治・国際機関", 88, "weekly"],
  ["Chatham House", "ThinkTank", "https://www.chathamhouse.org/rss.xml", "UK", "Global", "en", "政治・国際機関", 88, "daily"],
  ["Council on Foreign Relations", "ThinkTank", "https://www.cfr.org/rss.xml", "US", "Global", "en", "政治・国際機関", 88, "daily"],
  ["IISS", "ThinkTank", "https://www.iiss.org/rss", "UK", "Global", "en", "政治・国際機関", 86, "weekly"],
  ["Brookings Foreign Policy", "ThinkTank", "https://www.brookings.edu/feed/", "US", "Global", "en", "政治・国際機関", 87, "daily"],
  ["Carnegie Endowment", "ThinkTank", "https://carnegieendowment.org/rss/solr/?fa=feeds", "US", "Global", "en", "政治・国際機関", 87, "daily"]
];

const economicSources: SourceSeed[] = [
  ["IMF", "InternationalOrganization", "https://www.imf.org/en/News/RSS", "Global", "Global", "en", "経済・金融", 95, "daily"],
  ["World Bank", "InternationalOrganization", "https://www.worldbank.org/en/news/all/rss", "Global", "Global", "en", "経済・金融", 94, "daily"],
  ["BIS", "InternationalOrganization", "https://www.bis.org/list/press_releases/index.rss", "Global", "Global", "en", "経済・金融", 94, "daily"],
  ["Federal Reserve", "Government", "https://www.federalreserve.gov/feeds/press_all.xml", "US", "North America", "en", "経済・金融", 95, "daily"],
  ["European Central Bank", "Government", "https://www.ecb.europa.eu/rss/press.html", "EU", "Europe", "en", "経済・金融", 94, "daily"],
  ["Bank of Japan", "Government", "https://www.boj.or.jp/rss/whatsnew.xml", "JP", "Asia", "ja", "経済・金融", 95, "daily"],
  ["US Treasury", "Government", "https://home.treasury.gov/news/press-releases", "US", "North America", "en", "経済・金融", 93, "daily"],
  ["US Bureau of Economic Analysis", "Government", "https://www.bea.gov/news", "US", "North America", "en", "経済・金融", 92, "daily"],
  ["US Bureau of Labor Statistics", "Government", "https://www.bls.gov/bls/news-release/home.htm", "US", "North America", "en", "経済・金融", 92, "daily"],
  ["FRED Blog", "Government", "https://fredblog.stlouisfed.org/feed/", "US", "North America", "en", "経済・金融", 89, "weekly"],
  ["OECD Economy", "InternationalOrganization", "https://www.oecd.org/economy/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "経済・金融", 91, "weekly"],
  ["OECD Tax", "InternationalOrganization", "https://www.oecd.org/tax/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "経済・金融", 89, "weekly"],
  ["World Trade Organization", "InternationalOrganization", "https://www.wto.org/english/news_e/news_e.htm", "Global", "Global", "en", "経済・金融", 90, "daily"],
  ["International Energy Agency", "InternationalOrganization", "https://www.iea.org/news", "Global", "Global", "en", "経済・金融", 89, "daily"],
  ["UNCTAD", "InternationalOrganization", "https://unctad.org/news", "Global", "Global", "en", "経済・金融", 88, "daily"],
  ["Asian Development Bank", "InternationalOrganization", "https://www.adb.org/news", "Asia", "Asia", "en", "経済・金融", 89, "daily"],
  ["財務省", "Government", "https://www.mof.go.jp/rss/index.xml", "JP", "Asia", "ja", "経済・金融", 93, "daily"],
  ["経済産業省", "Government", "https://www.meti.go.jp/rss/main.xml", "JP", "Asia", "ja", "経済・金融", 92, "daily"],
  ["金融庁", "Government", "https://www.fsa.go.jp/news/", "JP", "Asia", "ja", "経済・金融", 92, "daily"],
  ["日本取引所グループ", "NewsMedia", "https://www.jpx.co.jp/news/", "JP", "Asia", "ja", "経済・金融", 86, "daily"],
  ["Nikkei Asia", "NewsMedia", "https://asia.nikkei.com/rss/feed/nar", "JP", "Asia", "en", "経済・金融", 83, "hourly"],
  ["Financial Times World Economy", "NewsMedia", "https://www.ft.com/world-economy", "Global", "Global", "en", "経済・金融", 82, "daily"],
  ["The Economist", "NewsMedia", "https://www.economist.com/", "Global", "Global", "en", "経済・金融", 82, "daily"],
  ["McKinsey Insights", "ThinkTank", "https://www.mckinsey.com/featured-insights", "Global", "Global", "en", "経済・金融", 84, "weekly"],
  ["BCG Insights", "ThinkTank", "https://www.bcg.com/publications", "Global", "Global", "en", "経済・金融", 83, "weekly"],
  ["Deloitte Insights", "ThinkTank", "https://www2.deloitte.com/us/en/insights.html", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["Goldman Sachs Insights", "ThinkTank", "https://www.goldmansachs.com/insights/", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["BlackRock Insights", "ThinkTank", "https://www.blackrock.com/corporate/insights", "Global", "Global", "en", "経済・金融", 82, "weekly"],
  ["Peterson Institute", "ThinkTank", "https://www.piie.com/rss.xml", "US", "Global", "en", "経済・金融", 87, "daily"],
  ["Bruegel", "ThinkTank", "https://www.bruegel.org/rss.xml", "EU", "Europe", "en", "経済・金融", 86, "daily"]
];

const thoughtSources: SourceSeed[] = [
  ["Pew Research Center", "ThinkTank", "https://www.pewresearch.org/feed/", "US", "Global", "en", "思想・社会", 89, "daily"],
  ["World Values Survey", "Academic", "https://www.worldvaluessurvey.org/rss/rss.xml", "Global", "Global", "en", "思想・社会", 86, "weekly"],
  ["Our World in Data", "Academic", "https://ourworldindata.org/atom.xml", "Global", "Global", "en", "思想・社会", 89, "daily"],
  ["UNESCO", "InternationalOrganization", "https://www.unesco.org/en/rss.xml", "Global", "Global", "en", "思想・社会", 91, "daily"],
  ["UNESCO Social and Human Sciences", "InternationalOrganization", "https://www.unesco.org/en/social-human-sciences", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["OECD Society", "InternationalOrganization", "https://www.oecd.org/social/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["OECD Education", "InternationalOrganization", "https://www.oecd.org/education/publicationsdocuments/newsrelease/rss.xml", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["World Bank Education", "InternationalOrganization", "https://www.worldbank.org/en/topic/education/rss", "Global", "Global", "en", "思想・社会", 90, "weekly"],
  ["UNICEF Research", "InternationalOrganization", "https://www.unicef-irc.org/", "Global", "Global", "en", "思想・社会", 88, "weekly"],
  ["ILO News", "InternationalOrganization", "https://www.ilo.org/global/about-the-ilo/newsroom/news/lang--en/index.htm", "Global", "Global", "en", "思想・社会", 88, "daily"],
  ["Migration Policy Institute", "ThinkTank", "https://www.migrationpolicy.org/rss.xml", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["Gallup News", "ThinkTank", "https://news.gallup.com/rss.aspx", "US", "Global", "en", "思想・社会", 84, "daily"],
  ["Edelman Trust Barometer", "ThinkTank", "https://www.edelman.com/trust", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["Ipsos Global Advisor", "ThinkTank", "https://www.ipsos.com/en/global-advisor", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["DataReportal", "ThinkTank", "https://datareportal.com/reports", "Global", "Global", "en", "思想・社会", 82, "weekly"],
  ["Berkman Klein Center", "Academic", "https://cyber.harvard.edu/news", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["Stanford Center on Philanthropy and Civil Society", "Academic", "https://pacscenter.stanford.edu/research/", "US", "Global", "en", "思想・社会", 84, "weekly"],
  ["Harvard Kennedy School News", "Academic", "https://www.hks.harvard.edu/faculty-research/policy-topics", "US", "Global", "en", "思想・社会", 86, "weekly"],
  ["LSE Blogs", "Academic", "https://blogs.lse.ac.uk/", "UK", "Global", "en", "思想・社会", 84, "daily"],
  ["Brookings Social Policy", "ThinkTank", "https://www.brookings.edu/feed/", "US", "Global", "en", "思想・社会", 86, "daily"],
  ["Urban Institute", "ThinkTank", "https://www.urban.org/rss.xml", "US", "North America", "en", "思想・社会", 85, "weekly"],
  ["日本総研", "ThinkTank", "https://www.jri.co.jp/page.jsp?id=147", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["NIRA総合研究開発機構", "ThinkTank", "https://www.nira.or.jp/", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["リクルートワークス研究所", "ThinkTank", "https://www.works-i.com/", "JP", "Asia", "ja", "思想・社会", 84, "weekly"],
  ["文部科学省", "Government", "https://www.mext.go.jp/rss/news.xml", "JP", "Asia", "ja", "思想・社会", 93, "daily"],
  ["厚生労働省", "Government", "https://www.mhlw.go.jp/stf/news.rdf", "JP", "Asia", "ja", "思想・社会", 92, "daily"],
  ["こども家庭庁", "Government", "https://www.cfa.go.jp/news", "JP", "Asia", "ja", "思想・社会", 90, "daily"],
  ["文化庁", "Government", "https://www.bunka.go.jp/koho_hodo_oshirase/hodohappyo/", "JP", "Asia", "ja", "思想・社会", 89, "weekly"],
  ["内閣府 男女共同参画局", "Government", "https://www.gender.go.jp/public/index.html", "JP", "Asia", "ja", "思想・社会", 89, "weekly"],
  ["United Nations Population Fund", "InternationalOrganization", "https://www.unfpa.org/news", "Global", "Global", "en", "思想・社会", 88, "daily"]
];

const technologySources: SourceSeed[] = [
  ["OpenAI Blog", "Website", "https://openai.com/news/rss.xml", "US", "Global", "en", "テクノロジー", 90, "daily"],
  ["Google DeepMind Blog", "Website", "https://deepmind.google/discover/blog/rss.xml", "UK", "Global", "en", "テクノロジー", 90, "daily"],
  ["Google AI Blog", "Website", "https://blog.google/technology/ai/rss/", "US", "Global", "en", "テクノロジー", 88, "daily"],
  ["Microsoft AI Blog", "Website", "https://blogs.microsoft.com/ai/feed/", "US", "Global", "en", "テクノロジー", 88, "daily"],
  ["Meta AI Blog", "Website", "https://ai.meta.com/blog/", "US", "Global", "en", "テクノロジー", 87, "daily"],
  ["Anthropic News", "Website", "https://www.anthropic.com/news", "US", "Global", "en", "テクノロジー", 87, "daily"],
  ["NVIDIA Blog", "Website", "https://blogs.nvidia.com/feed/", "US", "Global", "en", "テクノロジー", 86, "daily"],
  ["Intel Newsroom", "Website", "https://www.intel.com/content/www/us/en/newsroom/home.html", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["AMD Newsroom", "Website", "https://www.amd.com/en/newsroom.html", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["TSMC News", "Website", "https://pr.tsmc.com/english/news", "TW", "Asia", "en", "テクノロジー", 85, "daily"],
  ["ASML News", "Website", "https://www.asml.com/en/news", "NL", "Europe", "en", "テクノロジー", 85, "daily"],
  ["MIT Technology Review", "NewsMedia", "https://www.technologyreview.com/feed/", "US", "Global", "en", "テクノロジー", 85, "daily"],
  ["IEEE Spectrum", "NewsMedia", "https://spectrum.ieee.org/feeds/feed.rss", "US", "Global", "en", "テクノロジー", 84, "daily"],
  ["Nature Machine Intelligence", "Academic", "https://www.nature.com/natmachintell/", "Global", "Global", "en", "テクノロジー", 88, "weekly"],
  ["Science Robotics", "Academic", "https://www.science.org/journal/scirobotics", "Global", "Global", "en", "テクノロジー", 86, "weekly"],
  ["arXiv AI papers", "Academic", "http://export.arxiv.org/rss/cs.AI", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Machine Learning", "Academic", "http://export.arxiv.org/rss/cs.LG", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Computation and Language", "Academic", "http://export.arxiv.org/rss/cs.CL", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["arXiv Computer Vision", "Academic", "http://export.arxiv.org/rss/cs.CV", "Global", "Global", "en", "テクノロジー", 88, "daily"],
  ["Stanford HAI", "Academic", "https://hai.stanford.edu/news/rss.xml", "US", "Global", "en", "テクノロジー", 89, "weekly"],
  ["MIT CSAIL News", "Academic", "https://www.csail.mit.edu/news", "US", "Global", "en", "テクノロジー", 88, "weekly"],
  ["Berkeley AI Research", "Academic", "https://bair.berkeley.edu/blog/", "US", "Global", "en", "テクノロジー", 87, "weekly"],
  ["Allen Institute for AI", "Academic", "https://allenai.org/blog", "US", "Global", "en", "テクノロジー", 87, "weekly"],
  ["OECD AI Policy Observatory", "InternationalOrganization", "https://oecd.ai/en/wonk", "Global", "Global", "en", "テクノロジー", 89, "weekly"],
  ["NIST AI", "Government", "https://www.nist.gov/artificial-intelligence", "US", "North America", "en", "テクノロジー", 90, "weekly"],
  ["DARPA News", "Government", "https://www.darpa.mil/news", "US", "North America", "en", "テクノロジー", 88, "weekly"],
  ["National Science Foundation News", "Government", "https://new.nsf.gov/news", "US", "North America", "en", "テクノロジー", 88, "weekly"],
  ["EU AI Office", "Government", "https://digital-strategy.ec.europa.eu/en/policies/ai-office", "EU", "Europe", "en", "テクノロジー", 89, "weekly"],
  ["デジタル庁 AI", "Government", "https://www.digital.go.jp/policies/ai", "JP", "Asia", "ja", "テクノロジー", 90, "weekly"],
  ["IPA 情報処理推進機構", "Government", "https://www.ipa.go.jp/news/", "JP", "Asia", "ja", "テクノロジー", 88, "daily"],
  ["NICT News", "Government", "https://www.nict.go.jp/press/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["産総研", "Government", "https://www.aist.go.jp/aist_j/news/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["理化学研究所", "Academic", "https://www.riken.jp/press/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["JST News", "Government", "https://www.jst.go.jp/pr/", "JP", "Asia", "ja", "テクノロジー", 87, "weekly"],
  ["MIT Sloan Management Review AI", "NewsMedia", "https://sloanreview.mit.edu/tag/artificial-intelligence/", "US", "Global", "en", "テクノロジー", 84, "weekly"]
];

const countryLayerSources: SourceSeed[] = [
  ["China State Council", "Government", "https://english.www.gov.cn/news/", "CN", "Asia", "en", "政治・国際機関", 89, "daily"],
  ["China Ministry of Foreign Affairs", "Government", "https://www.mfa.gov.cn/eng/wjdt_665385/", "CN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["National Bureau of Statistics of China", "Government", "https://www.stats.gov.cn/english/PressRelease/", "CN", "Asia", "en", "経済・金融", 89, "daily"],
  ["People's Bank of China", "Government", "https://www.pbc.gov.cn/en/3688110/3688172/index.html", "CN", "Asia", "en", "経済・金融", 89, "daily"],
  ["China Academy of Information and Communications Technology", "ThinkTank", "http://www.caict.ac.cn/english/research/", "CN", "Asia", "en", "テクノロジー", 84, "weekly"],
  ["Tsinghua University News", "Academic", "https://www.tsinghua.edu.cn/en/info/1245/1237.htm", "CN", "Asia", "en", "思想・社会", 82, "weekly"],
  ["India Prime Minister's Office", "Government", "https://www.pmindia.gov.in/en/news_updates/", "IN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["India Ministry of External Affairs", "Government", "https://www.mea.gov.in/press-releases.htm", "IN", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Reserve Bank of India", "Government", "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx", "IN", "Asia", "en", "経済・金融", 90, "daily"],
  ["NITI Aayog", "Government", "https://www.niti.gov.in/press-releases", "IN", "Asia", "en", "経済・金融", 87, "weekly"],
  ["India Ministry of Electronics and IT", "Government", "https://www.meity.gov.in/news", "IN", "Asia", "en", "テクノロジー", 87, "weekly"],
  ["Observer Research Foundation", "ThinkTank", "https://www.orfonline.org/feed", "IN", "Asia", "en", "思想・社会", 85, "daily"],
  ["UK Government News", "Government", "https://www.gov.uk/search/news-and-communications", "UK", "Europe", "en", "政治・国際機関", 90, "daily"],
  ["Bank of England", "Government", "https://www.bankofengland.co.uk/news", "UK", "Europe", "en", "経済・金融", 91, "daily"],
  ["Office for National Statistics", "Government", "https://www.ons.gov.uk/news", "UK", "Europe", "en", "経済・金融", 90, "daily"],
  ["UK AI Safety Institute", "Government", "https://www.aisi.gov.uk/news", "UK", "Europe", "en", "テクノロジー", 89, "weekly"],
  ["The Alan Turing Institute", "Academic", "https://www.turing.ac.uk/news", "UK", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["King's College London Policy Institute", "Academic", "https://www.kcl.ac.uk/policy-institute", "UK", "Europe", "en", "思想・社会", 84, "weekly"],
  ["Germany Federal Government", "Government", "https://www.bundesregierung.de/breg-en/news", "DE", "Europe", "en", "政治・国際機関", 89, "daily"],
  ["Deutsche Bundesbank", "Government", "https://www.bundesbank.de/en/press", "DE", "Europe", "en", "経済・金融", 91, "daily"],
  ["Destatis Germany", "Government", "https://www.destatis.de/EN/Press/Press.html", "DE", "Europe", "en", "経済・金融", 90, "daily"],
  ["Germany Federal Ministry of Education and Research", "Government", "https://www.bmbf.de/bmbf/en/home/home_node.html", "DE", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["Fraunhofer News", "Academic", "https://www.fraunhofer.de/en/press.html", "DE", "Europe", "en", "テクノロジー", 87, "weekly"],
  ["Bertelsmann Stiftung", "ThinkTank", "https://www.bertelsmann-stiftung.de/en/our-projects", "DE", "Europe", "en", "思想・社会", 84, "weekly"],
  ["France Government News", "Government", "https://www.gouvernement.fr/en/news", "FR", "Europe", "en", "政治・国際機関", 88, "daily"],
  ["Banque de France", "Government", "https://www.banque-france.fr/en/press-release", "FR", "Europe", "en", "経済・金融", 90, "daily"],
  ["INSEE France", "Government", "https://www.insee.fr/en/statistiques?debut=0", "FR", "Europe", "en", "経済・金融", 89, "daily"],
  ["Inria News", "Academic", "https://www.inria.fr/en/news", "FR", "Europe", "en", "テクノロジー", 86, "weekly"],
  ["Sciences Po Research", "Academic", "https://www.sciencespo.fr/en/research/", "FR", "Europe", "en", "思想・社会", 84, "weekly"],
  ["Korea Government", "Government", "https://www.korea.net/Government/Briefing-Room/Press-Releases", "KR", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Bank of Korea", "Government", "https://www.bok.or.kr/eng/bbs/E0000634/list.do", "KR", "Asia", "en", "経済・金融", 90, "daily"],
  ["Korea Statistics", "Government", "https://kostat.go.kr/anse/", "KR", "Asia", "en", "経済・金融", 88, "weekly"],
  ["Korea Ministry of Science and ICT", "Government", "https://www.msit.go.kr/eng/bbs/list.do?sCode=eng&mId=4&mPid=2", "KR", "Asia", "en", "テクノロジー", 88, "weekly"],
  ["Korea Development Institute", "ThinkTank", "https://www.kdi.re.kr/kdi_eng/main/main.jsp", "KR", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Taiwan Executive Yuan", "Government", "https://english.ey.gov.tw/News3", "TW", "Asia", "en", "政治・国際機関", 88, "daily"],
  ["Taiwan Central Bank", "Government", "https://www.cbc.gov.tw/en/mp-2.html", "TW", "Asia", "en", "経済・金融", 88, "weekly"],
  ["Taiwan National Development Council", "Government", "https://www.ndc.gov.tw/en/News.aspx", "TW", "Asia", "en", "経済・金融", 87, "weekly"],
  ["Taiwan Ministry of Digital Affairs", "Government", "https://moda.gov.tw/en/press/press-releases/607", "TW", "Asia", "en", "テクノロジー", 88, "weekly"],
  ["Academia Sinica", "Academic", "https://www.sinica.edu.tw/en/news", "TW", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Singapore Government News", "Government", "https://www.gov.sg/news", "SG", "Asia", "en", "政治・国際機関", 89, "daily"],
  ["Monetary Authority of Singapore", "Government", "https://www.mas.gov.sg/news", "SG", "Asia", "en", "経済・金融", 91, "daily"],
  ["Singapore Department of Statistics", "Government", "https://www.singstat.gov.sg/whats-new/latest-news", "SG", "Asia", "en", "経済・金融", 88, "weekly"],
  ["AI Singapore", "Academic", "https://aisingapore.org/news/", "SG", "Asia", "en", "テクノロジー", 87, "weekly"],
  ["Institute of Policy Studies Singapore", "ThinkTank", "https://lkyspp.nus.edu.sg/ips", "SG", "Asia", "en", "思想・社会", 84, "weekly"],
  ["Brazil Government News", "Government", "https://www.gov.br/planalto/en/latest-news", "BR", "South America", "en", "政治・国際機関", 86, "daily"],
  ["Central Bank of Brazil", "Government", "https://www.bcb.gov.br/en/press", "BR", "South America", "en", "経済・金融", 89, "daily"],
  ["IBGE News Agency", "Government", "https://agenciadenoticias.ibge.gov.br/en/agencia-news", "BR", "South America", "en", "経済・金融", 87, "weekly"],
  ["Brazil Ministry of Science Technology and Innovation", "Government", "https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/noticias", "BR", "South America", "pt", "テクノロジー", 85, "weekly"],
  ["Ipea Brazil", "ThinkTank", "https://www.ipea.gov.br/portal/", "BR", "South America", "pt", "思想・社会", 84, "weekly"]
];

const emergingRegionSources: SourceSeed[] = [
  ["Indonesia Cabinet Secretariat", "Government", "https://setkab.go.id/en/category/news/", "ID", "Southeast Asia", "en", "政治・国際機関", 86, "daily"],
  ["Bank Indonesia", "Government", "https://www.bi.go.id/en/publikasi/ruang-media/news-release/Default.aspx", "ID", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Statistics Indonesia", "Government", "https://www.bps.go.id/en/pressrelease", "ID", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["Indonesia Ministry of Communication and Digital Affairs", "Government", "https://www.komdigi.go.id/", "ID", "Southeast Asia", "id", "テクノロジー", 84, "weekly"],
  ["CSIS Indonesia", "ThinkTank", "https://www.csis.or.id/", "ID", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Vietnam Government News", "Government", "https://en.baochinhphu.vn/", "VN", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["State Bank of Vietnam", "Government", "https://www.sbv.gov.vn/webcenter/portal/en/home/sbv/news", "VN", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["General Statistics Office Vietnam", "Government", "https://www.gso.gov.vn/en/data-and-statistics/", "VN", "Southeast Asia", "en", "経済・金融", 86, "weekly"],
  ["Vietnam Ministry of Science and Technology", "Government", "https://www.most.gov.vn/en/Pages/home.aspx", "VN", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Vietnam Academy of Social Sciences", "Academic", "https://en.vass.gov.vn/", "VN", "Southeast Asia", "en", "思想・社会", 82, "weekly"],
  ["Thailand Government Public Relations", "Government", "https://thailand.prd.go.th/en", "TH", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bank of Thailand", "Government", "https://www.bot.or.th/en/news-and-media/news.html", "TH", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["National Statistical Office Thailand", "Government", "https://www.nso.go.th/nsoweb/index?set_lang=en", "TH", "Southeast Asia", "en", "経済・金融", 84, "weekly"],
  ["Thailand Digital Economy Promotion Agency", "Government", "https://www.depa.or.th/en/news", "TH", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Thailand Development Research Institute", "ThinkTank", "https://tdri.or.th/en/", "TH", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Malaysia Prime Minister Office", "Government", "https://www.pmo.gov.my/news/", "MY", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bank Negara Malaysia", "Government", "https://www.bnm.gov.my/press-releases", "MY", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Department of Statistics Malaysia", "Government", "https://www.dosm.gov.my/portal-main/release-content", "MY", "Southeast Asia", "en", "経済・金融", 85, "weekly"],
  ["Malaysia Digital Economy Corporation", "Government", "https://mdec.my/news", "MY", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Khazanah Research Institute", "ThinkTank", "https://www.krinstitute.org/", "MY", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Philippines Official Gazette", "Government", "https://www.officialgazette.gov.ph/", "PH", "Southeast Asia", "en", "政治・国際機関", 85, "daily"],
  ["Bangko Sentral ng Pilipinas", "Government", "https://www.bsp.gov.ph/SitePages/MediaAndResearch/MediaList.aspx", "PH", "Southeast Asia", "en", "経済・金融", 88, "daily"],
  ["Philippine Statistics Authority", "Government", "https://psa.gov.ph/statistics/press-releases", "PH", "Southeast Asia", "en", "経済・金融", 85, "weekly"],
  ["Philippines DICT", "Government", "https://dict.gov.ph/news/", "PH", "Southeast Asia", "en", "テクノロジー", 84, "weekly"],
  ["Philippine Institute for Development Studies", "ThinkTank", "https://www.pids.gov.ph/", "PH", "Southeast Asia", "en", "思想・社会", 84, "weekly"],
  ["Nigeria State House", "Government", "https://statehouse.gov.ng/news/", "NG", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Nigeria", "Government", "https://www.cbn.gov.ng/Out/News.asp", "NG", "Africa", "en", "経済・金融", 86, "daily"],
  ["National Bureau of Statistics Nigeria", "Government", "https://www.nigerianstat.gov.ng/news", "NG", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Nigeria National Information Technology Development Agency", "Government", "https://nitda.gov.ng/news/", "NG", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["Centre for Democracy and Development West Africa", "ThinkTank", "https://cddwestafrica.org/", "NG", "Africa", "en", "思想・社会", 83, "weekly"],
  ["South Africa Presidency", "Government", "https://www.thepresidency.gov.za/press-statements", "ZA", "Africa", "en", "政治・国際機関", 85, "daily"],
  ["South African Reserve Bank", "Government", "https://www.resbank.co.za/en/home/publications/publication-detail-pages/media-releases", "ZA", "Africa", "en", "経済・金融", 88, "daily"],
  ["Statistics South Africa", "Government", "https://www.statssa.gov.za/?page_id=1854", "ZA", "Africa", "en", "経済・金融", 85, "weekly"],
  ["South Africa Department of Communications and Digital Technologies", "Government", "https://www.dcdt.gov.za/media-room/media-statements.html", "ZA", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["Institute for Security Studies Africa", "ThinkTank", "https://issafrica.org/iss-today", "ZA", "Africa", "en", "思想・社会", 85, "weekly"],
  ["Kenya State House", "Government", "https://www.president.go.ke/news/", "KE", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Kenya", "Government", "https://www.centralbank.go.ke/media-center/", "KE", "Africa", "en", "経済・金融", 86, "daily"],
  ["Kenya National Bureau of Statistics", "Government", "https://www.knbs.or.ke/news/", "KE", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Kenya ICT Authority", "Government", "https://icta.go.ke/media-center/news/", "KE", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["African Population and Health Research Center", "ThinkTank", "https://aphrc.org/news/", "KE", "Africa", "en", "思想・社会", 84, "weekly"],
  ["Egypt State Information Service", "Government", "https://www.sis.gov.eg/section/0/501?lang=en-us", "EG", "Africa", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Egypt", "Government", "https://www.cbe.org.eg/en/news-publications/news", "EG", "Africa", "en", "経済・金融", 86, "daily"],
  ["CAPMAS Egypt", "Government", "https://www.capmas.gov.eg/HomePage.aspx?lang=2", "EG", "Africa", "en", "経済・金融", 84, "weekly"],
  ["Egypt Information Technology Industry Development Agency", "Government", "https://www.itida.gov.eg/English/MediaCenter/News/Pages/default.aspx", "EG", "Africa", "en", "テクノロジー", 84, "weekly"],
  ["AUC Alternative Policy Solutions", "Academic", "https://aps.aucegypt.edu/en", "EG", "Africa", "en", "思想・社会", 83, "weekly"],
  ["Mexico Presidency", "Government", "https://www.gob.mx/presidencia/prensa", "MX", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Bank of Mexico", "Government", "https://www.banxico.org.mx/publications-and-press/press-releases/%7B0%7D", "MX", "Latin America", "en", "経済・金融", 88, "daily"],
  ["INEGI Mexico", "Government", "https://www.inegi.org.mx/app/saladeprensa/", "MX", "Latin America", "es", "経済・金融", 85, "weekly"],
  ["Mexico Digital Agency", "Government", "https://www.gob.mx/innovaciondigital", "MX", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["CIDE Mexico", "Academic", "https://www.cide.edu/", "MX", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Argentina Government", "Government", "https://www.argentina.gob.ar/noticias", "AR", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Central Bank of Argentina", "Government", "https://www.bcra.gob.ar/Noticias/", "AR", "Latin America", "es", "経済・金融", 86, "daily"],
  ["INDEC Argentina", "Government", "https://www.indec.gob.ar/indec/web/Institucional-Indec-Noticias", "AR", "Latin America", "es", "経済・金融", 85, "weekly"],
  ["Argentina Science and Technology", "Government", "https://www.argentina.gob.ar/ciencia/noticias", "AR", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["CIPPEC Argentina", "ThinkTank", "https://www.cippec.org/", "AR", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Chile Government", "Government", "https://www.gob.cl/en/news/", "CL", "Latin America", "en", "政治・国際機関", 84, "daily"],
  ["Central Bank of Chile", "Government", "https://www.bcentral.cl/en/web/banco-central/news", "CL", "Latin America", "en", "経済・金融", 87, "daily"],
  ["INE Chile", "Government", "https://www.ine.gob.cl/prensa", "CL", "Latin America", "es", "経済・金融", 84, "weekly"],
  ["Chile Ministry of Science", "Government", "https://www.minciencia.gob.cl/noticias/", "CL", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["Centro de Estudios Publicos Chile", "ThinkTank", "https://www.cepchile.cl/", "CL", "Latin America", "es", "思想・社会", 83, "weekly"],
  ["Colombia Presidency", "Government", "https://petro.presidencia.gov.co/prensa/Paginas/default.aspx", "CO", "Latin America", "es", "政治・国際機関", 84, "daily"],
  ["Banco de la Republica Colombia", "Government", "https://www.banrep.gov.co/en/news", "CO", "Latin America", "en", "経済・金融", 87, "daily"],
  ["DANE Colombia", "Government", "https://www.dane.gov.co/index.php/en/press-releases", "CO", "Latin America", "en", "経済・金融", 84, "weekly"],
  ["Colombia Ministry of ICT", "Government", "https://www.mintic.gov.co/portal/inicio/Sala-de-prensa/Noticias/", "CO", "Latin America", "es", "テクノロジー", 83, "weekly"],
  ["Fedesarrollo Colombia", "ThinkTank", "https://www.fedesarrollo.org.co/", "CO", "Latin America", "es", "思想・社会", 83, "weekly"]
];

export const initialSources: Source[] = [
  ...politicalSources,
  ...economicSources,
  ...thoughtSources,
  ...technologySources,
  ...countryLayerSources,
  ...emergingRegionSources
].map(([name, source_type, url, country, region, language, category, reliability_score, crawl_frequency], index) => ({
  id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  name,
  source_type,
  url,
  country,
  region,
  language,
  category,
  reliability_score,
  crawl_frequency,
  is_active: true,
  created_at: now
} as Source));
